-- P6 assessment questions: 82 questions
-- Source: New assessment question and answer/P6 Ax Question.pdf + Answer.pdf
-- All reference the unit's placeholder topic (lesson_number = unit_number).
-- source_paper = 'p6_ax_2026'

BEGIN;

DELETE FROM assessment_questions WHERE source_paper = 'p6_ax_2026';

INSERT INTO assessment_questions
  (topic_id, difficulty_tier, question_type, question_text, options, correct_answer,
   source_paper, source_question, is_active)
VALUES
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '根據商不變的性質,在括號裡填上合適的數:1.25 ÷ 0.25 = ( ) ÷ 25',
   NULL,
   '125',
   'p6_ax_2026', 'U1Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '根據商不變的性質,在括號裡填上合適的數:3.6 ÷ 0.12 = ( ) ÷ 12',
   NULL,
   '360',
   'p6_ax_2026', 'U1Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '根據商不變的性質,在括號裡填上合適的數:0.78 ÷ 0.06 = 78 ÷ ( )',
   NULL,
   '6',
   'p6_ax_2026', 'U1Q1c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '計算:10.8 ÷ 1.2 = ?',
   NULL,
   '9',
   'p6_ax_2026', 'U1Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '計算:2.52 ÷ 0.36 = ?',
   NULL,
   '7',
   'p6_ax_2026', 'U1Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '4.8 ÷ 2.3,結果保留一位小數,約等於多少?',
   NULL,
   '2.1',
   'p6_ax_2026', 'U1Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '10 ÷ 7,結果保留兩位小數,約等於多少?',
   NULL,
   '1.43',
   'p6_ax_2026', 'U1Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算:12.6 ÷ 0.7 - 1.8 × 3 = ?',
   NULL,
   '12.6',
   'p6_ax_2026', 'U1Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算:3.6 ÷ (1.2 + 0.6) × 0.5 = ?',
   NULL,
   '1',
   'p6_ax_2026', 'U1Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算:7.8 ÷ 0.25 ÷ 4 = ?',
   NULL,
   '7.8',
   'p6_ax_2026', 'U1Q5c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '香港某工廠生產一個零件需要 2.5 厘米的鐵絲,現有一根 42 厘米的鐵絲,最多可以生產多少個這樣的零件?',
   NULL,
   '16',
   'p6_ax_2026', 'U1Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個油桶最多可以裝 4.5 升油,現有 60 升油,至少需要多少個這樣的油桶才能全部裝完?',
   NULL,
   '14',
   'p6_ax_2026', 'U1Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'advanced', 'fill_in_number',
   '香港計程車首 2 公里收費 27 元,之後每 0.2 公里收費 1.9 元,李叔叔坐計程車付了 80 元,他最多坐了多少公里?',
   NULL,
   '7.4',
   'p6_ax_2026', 'U1Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '小明在計算一道小數除法時,把除數 0.6 看成了 6,結果得到的商是 0.25,正確的商應該是多少?',
   NULL,
   '2.5',
   'p6_ax_2026', 'U1Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '3 台抽水機 4 小時可以澆地 2.4 公頃,平均每台抽水機每小時可以澆地多少公頃?',
   NULL,
   '0.2',
   'p6_ax_2026', 'U1Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '媽媽用 500 港元兌換日圓,1 港元可以兌換 18.5 日圓,媽媽最多可以兌換多少日圓?',
   NULL,
   '9250',
   'p6_ax_2026', 'U1Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '寫出下列百分數:百分之六十五',
   '["A. 65%", "B. 6.5%", "C. 0.65%", "D. 650%"]'::jsonb,
   'A. 65%',
   'p6_ax_2026', 'U2Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 0.45 化成百分數',
   '["A. 4.5%", "B. 45%", "C. 0.45%", "D. 450%"]'::jsonb,
   'B. 45%',
   'p6_ax_2026', 'U2Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 1.2 化成百分數',
   '["A. 12%", "B. 1.2%", "C. 120%", "D. 0.12%"]'::jsonb,
   'C. 120%',
   'p6_ax_2026', 'U2Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 0.03 化成百分數',
   '["A. 30%", "B. 0.3%", "C. 0.03%", "D. 3%"]'::jsonb,
   'D. 3%',
   'p6_ax_2026', 'U2Q3c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 3/4 化成百分數',
   '["A. 34%", "B. 75%", "C. 7.5%", "D. 43%"]'::jsonb,
   'B. 75%',
   'p6_ax_2026', 'U2Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 2/5 化成百分數',
   '["A. 25%", "B. 52%", "C. 40%", "D. 4%"]'::jsonb,
   'C. 40%',
   'p6_ax_2026', 'U2Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '把 72% 化成小數',
   NULL,
   '0.72',
   'p6_ax_2026', 'U2Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '把 150% 化成小數',
   NULL,
   '1.5',
   'p6_ax_2026', 'U2Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '把 4.5% 化成小數',
   NULL,
   '0.045',
   'p6_ax_2026', 'U2Q5c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 25% 化成最簡分數',
   '["A. 1/4", "B. 1/5", "C. 25/100", "D. 1/3"]'::jsonb,
   'A. 1/4',
   'p6_ax_2026', 'U2Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 40% 化成最簡分數',
   '["A. 4/10", "B. 1/4", "C. 2/5", "D. 4/5"]'::jsonb,
   'C. 2/5',
   'p6_ax_2026', 'U2Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'enhancement', 'multiple_choice',
   '把 125% 化成最簡分數(假分數)',
   '["A. 1/4", "B. 5/4", "C. 4/5", "D. 25/4"]'::jsonb,
   'B. 5/4',
   'p6_ax_2026', 'U2Q6c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '六年級一班有 50 名學生,今天有 48 人出席,求今天的出席率(以百分數表示)。',
   NULL,
   '96%',
   'p6_ax_2026', 'U2Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '種子站做發芽實驗,用 200 粒種子做實驗,有 195 粒發芽,求發芽率(以百分數表示)。',
   NULL,
   '97.5%',
   'p6_ax_2026', 'U2Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'enhancement', 'fill_in_number',
   '六年級二班數學考試,合格的有 45 人,不合格的有 5 人,求這次考試的合格率(以百分數表示)。',
   NULL,
   '90%',
   'p6_ax_2026', 'U2Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'enhancement', 'fill_in_number',
   '某工廠生產一批零件,經檢驗有 198 個合格,合格率是 99%,這批零件一共有多少個?',
   NULL,
   '200',
   'p6_ax_2026', 'U2Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察等差數列:3, 7, 11, 15, ( ), 23,括號裡的數是多少?',
   NULL,
   '19',
   'p6_ax_2026', 'U3Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察等差數列:45, 40, 35, 30, ( ), 20,括號裡的數是多少?',
   NULL,
   '25',
   'p6_ax_2026', 'U3Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察等比數列:2, 4, 8, 16, ( ), 64,括號裡的數是多少?',
   NULL,
   '32',
   'p6_ax_2026', 'U3Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察等比數列:96, 48, 24, 12, ( ),括號裡的數是多少?',
   NULL,
   '6',
   'p6_ax_2026', 'U3Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '觀察三角形數列:1, 3, 6, 10, ( ), 21, 28,括號裡的數是多少?',
   NULL,
   '15',
   'p6_ax_2026', 'U3Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察平方數數列:1, 4, 9, 16, ( ), 36, 49,括號裡的數是多少?',
   NULL,
   '25',
   'p6_ax_2026', 'U3Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '觀察二階等差數列:1, 2, 4, 7, 11, ( ), 22,括號裡的數是多少?',
   NULL,
   '16',
   'p6_ax_2026', 'U3Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '觀察二階等差數列:2, 5, 11, 20, 32, ( ), 65,括號裡的數是多少?',
   NULL,
   '47',
   'p6_ax_2026', 'U3Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'advanced', 'fill_in_number',
   '觀察數列規律,補全缺失項:1, 3, 7, 15, 31, ( ), 127',
   NULL,
   '63',
   'p6_ax_2026', 'U3Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '等差數列 2, 5, 8, 11…… 的第 10 項是多少?',
   NULL,
   '29',
   'p6_ax_2026', 'U3Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'advanced', 'fill_in_number',
   '等比數列 3, 6, 12, 24…… 的第 10 項是多少?',
   NULL,
   '1536',
   'p6_ax_2026', 'U3Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '有一列數:2, 5, 8, 11, 14……,請問 104 是這列數中的第幾個數?',
   NULL,
   '35',
   'p6_ax_2026', 'U3Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察斐波那契數列:1, 1, 2, 3, 5, 8, ( ), 21, 34,括號裡的數是多少?',
   NULL,
   '13',
   'p6_ax_2026', 'U3Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個數列的第 n 項公式是 n²+2n,這個數列的第 5 項是多少?',
   NULL,
   '35',
   'p6_ax_2026', 'U3Q12a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個數列的第 n 項公式是 n²+2n,這個數列的第 10 項是多少?',
   NULL,
   '120',
   'p6_ax_2026', 'U3Q12b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '一個圓的半徑是 6 厘米,它的直徑是多少厘米?',
   NULL,
   '12',
   'p6_ax_2026', 'U4Q4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '一個圓的直徑是 12 分米,它的半徑是多少分米?',
   NULL,
   '6',
   'p6_ax_2026', 'U4Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '畫一個直徑是 8 厘米的圓,圓規兩腳之間的距離應該是多少厘米?',
   NULL,
   '4',
   'p6_ax_2026', 'U4Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'fill_in_number',
   '在一個長 12 厘米、闊 8 厘米的長方形紙裡,畫一個最大的圓,這個圓的直徑是多少厘米?',
   NULL,
   '8',
   'p6_ax_2026', 'U4Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'fill_in_number',
   '在一個長 12 厘米、闊 8 厘米的長方形紙裡,畫一個最大的圓,這個圓的半徑是多少厘米?',
   NULL,
   '4',
   'p6_ax_2026', 'U4Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '在一個邊長是 10 厘米的正方形紙裡,畫一個最大的圓,這個圓的直徑是多少厘米?',
   NULL,
   '10',
   'p6_ax_2026', 'U4Q9a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '在一個邊長是 10 厘米的正方形紙裡,畫一個最大的圓,這個圓的半徑是多少厘米?',
   NULL,
   '5',
   'p6_ax_2026', 'U4Q9b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'fill_in_number',
   '圓內畫了一個三角形,其中一個頂點是圓心 O,另外兩個頂點 A、B 在圓周上,已知 OA=5 厘米,OB 的長度是多少厘米?',
   NULL,
   '5',
   'p6_ax_2026', 'U4Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'advanced', 'fill_in_number',
   '圓內有一個等腰三角形 OAB,頂點 O 是圓心,已知 ∠OAB=40°,求頂角 ∠AOB 的度數。',
   NULL,
   '100',
   'p6_ax_2026', 'U4Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '一個圓的直徑擴大到原來的 4 倍,它的半徑擴大到原來的多少倍?',
   NULL,
   '4',
   'p6_ax_2026', 'U4Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'multiple_choice',
   '兩個圓的半徑分別是 3 厘米和 5 厘米,它們的直徑比是多少?',
   '["A. 5:3", "B. 3:5", "C. 6:10", "D. 9:25"]'::jsonb,
   'B. 3:5',
   'p6_ax_2026', 'U4Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '正三角形有多少條對稱軸?',
   NULL,
   '3',
   'p6_ax_2026', 'U5Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '正方形有多少條對稱軸?',
   NULL,
   '4',
   'p6_ax_2026', 'U5Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '正五邊形有多少條對稱軸?',
   NULL,
   '5',
   'p6_ax_2026', 'U5Q3c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '正六邊形有多少條對稱軸?',
   NULL,
   '6',
   'p6_ax_2026', 'U5Q3d', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '等邊三角形是幾折旋轉對稱圖形?',
   NULL,
   '3',
   'p6_ax_2026', 'U5Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '正方形是幾折旋轉對稱圖形?',
   NULL,
   '4',
   'p6_ax_2026', 'U5Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '長方形是幾折旋轉對稱圖形?',
   NULL,
   '2',
   'p6_ax_2026', 'U5Q5c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '平行四邊形是幾折旋轉對稱圖形?',
   NULL,
   '2',
   'p6_ax_2026', 'U5Q5d', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個圖形繞旋轉中心旋轉 60° 後能與原圖重合,這個圖形是幾折旋轉對稱圖形?',
   NULL,
   '6',
   'p6_ax_2026', 'U5Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個 4 折旋轉對稱圖形,繞旋轉中心旋轉多少度後能與原圖重合?',
   NULL,
   '90',
   'p6_ax_2026', 'U5Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'basic', 'fill_in_number',
   '1 升 = ( ) 毫升',
   NULL,
   '1000',
   'p6_ax_2026', 'U6Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'basic', 'fill_in_number',
   '1 立方米 = ( ) 立方分米',
   NULL,
   '1000',
   'p6_ax_2026', 'U6Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'basic', 'fill_in_number',
   '3.5 升 = ( ) 毫升',
   NULL,
   '3500',
   'p6_ax_2026', 'U6Q1c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'basic', 'fill_in_number',
   '4800 立方厘米 = ( ) 升',
   NULL,
   '4.8',
   'p6_ax_2026', 'U6Q1d', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體容器,從裡面量長 8 分米,闊 5 分米,高 4 分米,這個容器的容積是多少升?',
   NULL,
   '160',
   'p6_ax_2026', 'U6Q2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'basic', 'fill_in_number',
   '一個正方體水箱,棱長是 6 米,它的容積是多少立方米?',
   NULL,
   '216',
   'p6_ax_2026', 'U6Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體玻璃缸,長 30 厘米,闊 20 厘米,裡面裝了 10 厘米深的水,將一塊石頭完全浸入水中,水面上升到 12 厘米,這塊石頭的體積是多少立方厘米?',
   NULL,
   '1200',
   'p6_ax_2026', 'U6Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體魚缸,從裡面量長 60 厘米,闊 40 厘米,高 50 厘米,這個魚缸最多能裝多少升水?',
   NULL,
   '120',
   'p6_ax_2026', 'U6Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'advanced', 'fill_in_number',
   '一個正方體容器,棱長是 20 厘米,裡面裝滿了水,把水全部倒入一個長 40 厘米、闊 25 厘米的長方體容器中,水深多少厘米?',
   NULL,
   '8',
   'p6_ax_2026', 'U6Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'advanced', 'fill_in_number',
   '一個長方體容器,底面積是 120 平方厘米,高是 10 厘米,裡面裝了 8 厘米深的水,現在把一個石頭完全浸入水中,水溢出了 200 毫升,這塊石頭的體積是多少立方厘米?',
   NULL,
   '440',
   'p6_ax_2026', 'U6Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'enhancement', 'fill_in_number',
   '把 3 個棱長是 2 分米的正方體拼成一個長方體,這個長方體的體積是多少立方分米?',
   NULL,
   '24',
   'p6_ax_2026', 'U6Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體的容積是 240 升,它的長是 8 分米,闊是 6 分米,高是多少分米?',
   NULL,
   '5',
   'p6_ax_2026', 'U6Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=7 AND t.lesson_number=7 LIMIT 1), 'basic', 'fill_in_number',
   '計算半徑 r=5 厘米的圓的周長(π 取 3.14)。答案是多少厘米?',
   NULL,
   '31.4',
   'p6_ax_2026', 'U7Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=7 AND t.lesson_number=7 LIMIT 1), 'basic', 'fill_in_number',
   '計算直徑 d=12 分米的圓的周長(π 取 3.14)。答案是多少分米?',
   NULL,
   '37.68',
   'p6_ax_2026', 'U7Q2b', true);

COMMIT;

-- Sanity: SELECT count(*) FROM assessment_questions WHERE source_paper='p6_ax_2026' AND is_active;
-- Expect: 82