-- P6 assessment questions: 179 questions
-- Source: New assessment question and answer/P6 Ax Question.pdf + Answer.pdf
-- All reference the unit's placeholder topic (lesson_number = unit_number).
-- source_paper = 'p6_ax_2026'

BEGIN;

DELETE FROM assessment_questions WHERE source_paper = 'p6_ax_2026';

INSERT INTO assessment_questions
  (topic_id, difficulty_tier, question_type, question_text, options, correct_answer,
   source_paper, source_question, is_active)
VALUES
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '根據商不變的性質,在括號裡填上合適的數:1.25 ÷ 0.25 = ( ) ÷ 25',
   NULL,
   '125',
   'p6_ax_2026', 'U1Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '根據商不變的性質,在括號裡填上合適的數:3.6 ÷ 0.12 = ( ) ÷ 12',
   NULL,
   '360',
   'p6_ax_2026', 'U1Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '根據商不變的性質,在括號裡填上合適的數:0.78 ÷ 0.06 = 78 ÷ ( )',
   NULL,
   '6',
   'p6_ax_2026', 'U1Q1c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '計算:10.8 ÷ 1.2 = ?',
   NULL,
   '9',
   'p6_ax_2026', 'U1Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '計算:2.52 ÷ 0.36 = ?',
   NULL,
   '7',
   'p6_ax_2026', 'U1Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '4.8 ÷ 2.3,結果保留一位小數,約等於多少?',
   NULL,
   '2.1',
   'p6_ax_2026', 'U1Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '10 ÷ 7,結果保留兩位小數,約等於多少?',
   NULL,
   '1.43',
   'p6_ax_2026', 'U1Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算:12.6 ÷ 0.7 - 1.8 × 3 = ?',
   NULL,
   '12.6',
   'p6_ax_2026', 'U1Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算:3.6 ÷ (1.2 + 0.6) × 0.5 = ?',
   NULL,
   '1',
   'p6_ax_2026', 'U1Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算:7.8 ÷ 0.25 ÷ 4 = ?',
   NULL,
   '7.8',
   'p6_ax_2026', 'U1Q5c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '香港某工廠生產一個零件需要 2.5 厘米的鐵絲,現有一根 42 厘米的鐵絲,最多可以生產多少個這樣的零件?',
   NULL,
   '16',
   'p6_ax_2026', 'U1Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個油桶最多可以裝 4.5 升油,現有 60 升油,至少需要多少個這樣的油桶才能全部裝完?',
   NULL,
   '14',
   'p6_ax_2026', 'U1Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'advanced', 'fill_in_number',
   '香港計程車首 2 公里收費 27 元,之後每 0.2 公里收費 1.9 元,李叔叔坐計程車付了 80 元,他最多坐了多少公里?',
   NULL,
   '7.4',
   'p6_ax_2026', 'U1Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '小明在計算一道小數除法時,把除數 0.6 看成了 6,結果得到的商是 0.25,正確的商應該是多少?',
   NULL,
   '2.5',
   'p6_ax_2026', 'U1Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '3 台抽水機 4 小時可以澆地 2.4 公頃,平均每台抽水機每小時可以澆地多少公頃?',
   NULL,
   '0.2',
   'p6_ax_2026', 'U1Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'fill_in_number',
   '媽媽用 500 港元兌換日圓,1 港元可以兌換 18.5 日圓,媽媽最多可以兌換多少日圓?',
   NULL,
   '9250',
   'p6_ax_2026', 'U1Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '寫出下列百分數:百分之六十五',
   '["A. 65%", "B. 6.5%", "C. 0.65%", "D. 650%"]'::jsonb,
   'A. 65%',
   'p6_ax_2026', 'U2Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 0.45 化成百分數',
   '["A. 4.5%", "B. 45%", "C. 0.45%", "D. 450%"]'::jsonb,
   'B. 45%',
   'p6_ax_2026', 'U2Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 1.2 化成百分數',
   '["A. 12%", "B. 1.2%", "C. 120%", "D. 0.12%"]'::jsonb,
   'C. 120%',
   'p6_ax_2026', 'U2Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 0.03 化成百分數',
   '["A. 30%", "B. 0.3%", "C. 0.03%", "D. 3%"]'::jsonb,
   'D. 3%',
   'p6_ax_2026', 'U2Q3c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 3/4 化成百分數',
   '["A. 30%", "B. 75%", "C. 7.5%", "D. 60%"]'::jsonb,
   'B. 75%',
   'p6_ax_2026', 'U2Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 2/5 化成百分數',
   '["A. 25%", "B. 80%", "C. 40%", "D. 0.4%"]'::jsonb,
   'C. 40%',
   'p6_ax_2026', 'U2Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '把 72% 化成小數',
   NULL,
   '0.72',
   'p6_ax_2026', 'U2Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '把 150% 化成小數',
   NULL,
   '1.5',
   'p6_ax_2026', 'U2Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '把 4.5% 化成小數',
   NULL,
   '0.045',
   'p6_ax_2026', 'U2Q5c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 25% 化成最簡分數',
   '["A. 1/4", "B. 1/5", "C. 1/25", "D. 1/3"]'::jsonb,
   'A. 1/4',
   'p6_ax_2026', 'U2Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'multiple_choice',
   '把 40% 化成最簡分數',
   '["A. 1/40", "B. 1/4", "C. 2/5", "D. 4/5"]'::jsonb,
   'C. 2/5',
   'p6_ax_2026', 'U2Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'enhancement', 'multiple_choice',
   '把 125% 化成最簡分數(假分數)',
   '["A. 1/4", "B. 5/4", "C. 4/5", "D. 25/4"]'::jsonb,
   'B. 5/4',
   'p6_ax_2026', 'U2Q6c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '六年級一班有 50 名學生,今天有 48 人出席,求今天的出席率(以百分數表示，只填數字)',
   NULL,
   '96',
   'p6_ax_2026', 'U2Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '種子站做發芽實驗,用 200 粒種子做實驗,有 195 粒發芽,求發芽率(以百分數表示，只填數字)',
   NULL,
   '97.5',
   'p6_ax_2026', 'U2Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'enhancement', 'fill_in_number',
   '六年級二班數學考試,合格的有 45 人,不合格的有 5 人,求這次考試的合格率(以百分數表示，只填數字)',
   NULL,
   '90',
   'p6_ax_2026', 'U2Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'enhancement', 'fill_in_number',
   '某工廠生產一批零件,經檢驗有 198 個合格,合格率是 99%,這批零件一共有多少個?',
   NULL,
   '200',
   'p6_ax_2026', 'U2Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察等差數列:3, 7, 11, 15, ( ), 23,括號裡的數是多少?',
   NULL,
   '19',
   'p6_ax_2026', 'U3Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察等差數列:45, 40, 35, 30, ( ), 20,括號裡的數是多少?',
   NULL,
   '25',
   'p6_ax_2026', 'U3Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察等比數列:2, 4, 8, 16, ( ), 64,括號裡的數是多少?',
   NULL,
   '32',
   'p6_ax_2026', 'U3Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察等比數列:96, 48, 24, 12, ( ),括號裡的數是多少?',
   NULL,
   '6',
   'p6_ax_2026', 'U3Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '觀察三角形數列:1, 3, 6, 10, ( ), 21, 28,括號裡的數是多少?',
   NULL,
   '15',
   'p6_ax_2026', 'U3Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察平方數數列:1, 4, 9, 16, ( ), 36, 49,括號裡的數是多少?',
   NULL,
   '25',
   'p6_ax_2026', 'U3Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '觀察二階等差數列:1, 2, 4, 7, 11, ( ), 22,括號裡的數是多少?',
   NULL,
   '16',
   'p6_ax_2026', 'U3Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '觀察二階等差數列:2, 5, 11, 20, 32, ( ), 65,括號裡的數是多少?',
   NULL,
   '47',
   'p6_ax_2026', 'U3Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'advanced', 'fill_in_number',
   '觀察數列規律,補全缺失項:1, 3, 7, 15, 31, ( ), 127',
   NULL,
   '63',
   'p6_ax_2026', 'U3Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '等差數列 2, 5, 8, 11…… 的第 10 項是多少?',
   NULL,
   '29',
   'p6_ax_2026', 'U3Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'advanced', 'fill_in_number',
   '等比數列 3, 6, 12, 24…… 的第 10 項是多少?',
   NULL,
   '1536',
   'p6_ax_2026', 'U3Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '有一列數:2, 5, 8, 11, 14……,請問 104 是這列數中的第幾個數?',
   NULL,
   '35',
   'p6_ax_2026', 'U3Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '觀察斐波那契數列:1, 1, 2, 3, 5, 8, ( ), 21, 34,括號裡的數是多少?',
   NULL,
   '13',
   'p6_ax_2026', 'U3Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個數列的第 n 項公式是 n²+2n,這個數列的第 5 項是多少?',
   NULL,
   '35',
   'p6_ax_2026', 'U3Q12a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個數列的第 n 項公式是 n²+2n,這個數列的第 10 項是多少?',
   NULL,
   '120',
   'p6_ax_2026', 'U3Q12b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '一個圓的半徑是 6 厘米,它的直徑是多少厘米?',
   NULL,
   '12',
   'p6_ax_2026', 'U4Q4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '一個圓的直徑是 12 分米,它的半徑是多少分米?',
   NULL,
   '6',
   'p6_ax_2026', 'U4Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '畫一個直徑是 8 厘米的圓,圓規兩腳之間的距離應該是多少厘米?',
   NULL,
   '4',
   'p6_ax_2026', 'U4Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'fill_in_number',
   '在一個長 12 厘米、闊 8 厘米的長方形紙裡,畫一個最大的圓,這個圓的直徑是多少厘米?',
   NULL,
   '8',
   'p6_ax_2026', 'U4Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'fill_in_number',
   '在一個長 12 厘米、闊 8 厘米的長方形紙裡,畫一個最大的圓,這個圓的半徑是多少厘米?',
   NULL,
   '4',
   'p6_ax_2026', 'U4Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '在一個邊長是 10 厘米的正方形紙裡,畫一個最大的圓,這個圓的直徑是多少厘米?',
   NULL,
   '10',
   'p6_ax_2026', 'U4Q9a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '在一個邊長是 10 厘米的正方形紙裡,畫一個最大的圓,這個圓的半徑是多少厘米?',
   NULL,
   '5',
   'p6_ax_2026', 'U4Q9b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'fill_in_number',
   '圓內畫了一個三角形,其中一個頂點是圓心 O,另外兩個頂點 A、B 在圓周上,已知 OA=5 厘米,OB 的長度是多少厘米?',
   NULL,
   '5',
   'p6_ax_2026', 'U4Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'advanced', 'fill_in_number',
   '圓內有一個等腰三角形 OAB,O 是圓心,OA 和 OB 都是半徑(所以 OA=OB)。已知 ∠OAB=40°,求頂角 ∠AOB 的度數。',
   NULL,
   '100',
   'p6_ax_2026', 'U4Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '一個圓的直徑擴大到原來的 4 倍,它的半徑擴大到原來的多少倍?',
   NULL,
   '4',
   'p6_ax_2026', 'U4Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'multiple_choice',
   '兩個圓的半徑分別是 3 厘米和 5 厘米,它們的直徑比是多少?',
   '["A. 5:3", "B. 3:5", "C. 9:25", "D. 6:25"]'::jsonb,
   'B. 3:5',
   'p6_ax_2026', 'U4Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '正三角形有多少條對稱軸?',
   NULL,
   '3',
   'p6_ax_2026', 'U5Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '正方形有多少條對稱軸?',
   NULL,
   '4',
   'p6_ax_2026', 'U5Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '正五邊形有多少條對稱軸?',
   NULL,
   '5',
   'p6_ax_2026', 'U5Q3c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '正六邊形有多少條對稱軸?',
   NULL,
   '6',
   'p6_ax_2026', 'U5Q3d', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '等邊三角形是幾折旋轉對稱圖形?',
   NULL,
   '3',
   'p6_ax_2026', 'U5Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '正方形是幾折旋轉對稱圖形?',
   NULL,
   '4',
   'p6_ax_2026', 'U5Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '長方形是幾折旋轉對稱圖形?',
   NULL,
   '2',
   'p6_ax_2026', 'U5Q5c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '平行四邊形是幾折旋轉對稱圖形?',
   NULL,
   '2',
   'p6_ax_2026', 'U5Q5d', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個圖形繞旋轉中心旋轉 60° 後能與原圖重合,這個圖形是幾折旋轉對稱圖形?',
   NULL,
   '6',
   'p6_ax_2026', 'U5Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個 4 折旋轉對稱圖形,繞旋轉中心旋轉多少度後能與原圖重合?',
   NULL,
   '90',
   'p6_ax_2026', 'U5Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'basic', 'fill_in_number',
   '1 升 = ( ) 毫升',
   NULL,
   '1000',
   'p6_ax_2026', 'U6Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'basic', 'fill_in_number',
   '1 立方米 = ( ) 立方分米',
   NULL,
   '1000',
   'p6_ax_2026', 'U6Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'basic', 'fill_in_number',
   '3.5 升 = ( ) 毫升',
   NULL,
   '3500',
   'p6_ax_2026', 'U6Q1c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'basic', 'fill_in_number',
   '4800 立方厘米 = ( ) 升',
   NULL,
   '4.8',
   'p6_ax_2026', 'U6Q1d', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體容器,從裡面量長 8 分米,闊 5 分米,高 4 分米,這個容器的容積是多少升?',
   NULL,
   '160',
   'p6_ax_2026', 'U6Q2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'basic', 'fill_in_number',
   '一個正方體水箱,棱長是 6 米,它的容積是多少立方米?',
   NULL,
   '216',
   'p6_ax_2026', 'U6Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體玻璃缸,長 30 厘米,闊 20 厘米,裡面裝了 10 厘米深的水,將一塊石頭完全浸入水中,水面上升到 12 厘米,這塊石頭的體積是多少立方厘米?',
   NULL,
   '1200',
   'p6_ax_2026', 'U6Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體魚缸,從裡面量長 60 厘米,闊 40 厘米,高 50 厘米,這個魚缸最多能裝多少升水?',
   NULL,
   '120',
   'p6_ax_2026', 'U6Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'advanced', 'fill_in_number',
   '一個正方體容器,棱長是 20 厘米,裡面裝滿了水,把水全部倒入一個長 40 厘米、闊 25 厘米的長方體容器中,水深多少厘米?',
   NULL,
   '8',
   'p6_ax_2026', 'U6Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'advanced', 'fill_in_number',
   '一個長方體容器,底面積是 120 平方厘米,高是 10 厘米,裡面裝了 8 厘米深的水,現在把一個石頭完全浸入水中,水溢出了 200 毫升,這塊石頭的體積是多少立方厘米?',
   NULL,
   '440',
   'p6_ax_2026', 'U6Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'enhancement', 'fill_in_number',
   '把 3 個棱長是 2 分米的正方體拼成一個長方體,這個長方體的體積是多少立方分米?',
   NULL,
   '24',
   'p6_ax_2026', 'U6Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=6 AND t.lesson_number=6 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體的容積是 240 升,它的長是 8 分米,闊是 6 分米,高是多少分米?',
   NULL,
   '5',
   'p6_ax_2026', 'U6Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=7 AND t.lesson_number=7 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算半徑 r=5 厘米的圓的周長(π 取 3.14)。答案是多少厘米?',
   NULL,
   '31.4',
   'p6_ax_2026', 'U7Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=7 AND t.lesson_number=7 LIMIT 1), 'basic', 'fill_in_number',
   '計算直徑 d=12 分米的圓的周長(π 取 3.14)。答案是多少分米?',
   NULL,
   '37.68',
   'p6_ax_2026', 'U7Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'basic', 'fill_in_number',
   '折線圖中，用 1 厘米的線段代表 5°C，那麼代表 20°C 的線段應該畫多少厘米？',
   NULL,
   '4',
   'p6_ax_2026', 'U8Q7a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'basic', 'fill_in_number',
   '折線圖中，用 1 厘米的線段代表 5°C，3 厘米長的線段代表多少 °C？',
   NULL,
   '15',
   'p6_ax_2026', 'U8Q7b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'fill_in_number',
   '折線圖展示了某公司 1 月到 6 月的營業額變化：

| 月份 | 營業額（萬元） |
| --- | --- |
| 1月 | 50 |
| 6月 | 200 |

請問該公司 1 月到 6 月平均每月營業額增長多少萬元？',
   NULL,
   '30',
   'p6_ax_2026', 'U8Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'basic', 'multiple_choice',
   '甲、乙兩名運動員 1000 米跑步訓練，甲用了 4 分鐘，乙用了 5 分鐘，請問誰的平均速率更快？',
   '["A. 乙", "B. 甲", "C. 一樣快", "D. 無法判斷"]'::jsonb,
   'B. 甲',
   'p6_ax_2026', 'U8Q9a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'fill_in_number',
   '甲、乙兩名運動員 1000 米跑步訓練，甲用了 4 分鐘，乙用了 5 分鐘，甲比乙的平均速率快多少米/分鐘？',
   NULL,
   '50',
   'p6_ax_2026', 'U8Q9b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'basic', 'fill_in_number',
   '一件衣服原價 800 元，現在打七五折出售，現在的售價是多少元？',
   NULL,
   '600',
   'p6_ax_2026', 'U9Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'basic', 'fill_in_number',
   '一件衣服原價 800 元，現在打七五折出售，便宜了多少元？',
   NULL,
   '200',
   'p6_ax_2026', 'U9Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'basic', 'fill_in_number',
   '一臺電視機原價 5000 元，現在促銷減價 15%，現在的售價是多少元？',
   NULL,
   '4250',
   'p6_ax_2026', 'U9Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'basic', 'fill_in_number',
   '一件商品的成本是 200 元，售價是 250 元，這件商品的利潤是多少元？',
   NULL,
   '50',
   'p6_ax_2026', 'U9Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '一件商品的成本是 200 元，售價是 250 元，這件商品的利潤率是多少？(以百分數表示，只填數字)',
   NULL,
   '25',
   'p6_ax_2026', 'U9Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '一件商品打六折後的售價是 360 元，這件商品的原價是多少元？',
   NULL,
   '600',
   'p6_ax_2026', 'U9Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'advanced', 'fill_in_number',
   '香港某樓盤房價先漲價 10%，再降價 10%，現在的房價是每平方米 19800 元，請問原來的房價是每平方米多少元？',
   NULL,
   '20000',
   'p6_ax_2026', 'U9Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'multiple_choice',
   '香港某樓盤房價先漲價 10%，再降價 10%，現在的房價和原來相比，是漲了還是跌了？',
   '["A. 漲了", "B. 不變", "C. 跌了", "D. 無法判斷"]'::jsonb,
   'C. 跌了',
   'p6_ax_2026', 'U9Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '媽媽把 50000 元存入銀行，定期 3 年，年利率是 2.5%，按單利息計算，到期時媽媽可以獲得利息多少元？',
   NULL,
   '3750',
   'p6_ax_2026', 'U9Q7a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '媽媽把 50000 元存入銀行，定期 3 年，年利率是 2.5%，按單利息計算，到期時的本利和一共多少元？',
   NULL,
   '53750',
   'p6_ax_2026', 'U9Q7b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '爸爸把 20000 元存入銀行，定期 2 年，到期時獲得利息 800 元，請問年利率是多少？(按單利息計算，以百分數表示，只填數字)',
   NULL,
   '2',
   'p6_ax_2026', 'U9Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'advanced', 'fill_in_number',
   '一件商品的成本是 400 元，商店按 50% 的利潤率定價，然後打八折出售，現在的售價是多少元？',
   NULL,
   '480',
   'p6_ax_2026', 'U9Q10a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'advanced', 'fill_in_number',
   '一件商品的成本是 400 元，商店按 50% 的利潤率定價，然後打八折出售，實際利潤率是多少？(以百分數表示，只填數字)',
   NULL,
   '20',
   'p6_ax_2026', 'U9Q10b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '一件衣服售價 300 元，可獲利 20%，這件衣服的成本是多少元？',
   NULL,
   '250',
   'p6_ax_2026', 'U9Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '香港某商場進行促銷活動，滿 1000 元減 200 元，相當於打了多少折？(只填數字，例如八折填 8)',
   NULL,
   '8',
   'p6_ax_2026', 'U9Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'advanced', 'fill_in_number',
   '李先生把一筆錢存入銀行，年利率是 3%，定期 5 年，到期時他一共獲得本利和 23000 元，請問李先生存入的本金是多少元？(按單利息計算)',
   NULL,
   '20000',
   'p6_ax_2026', 'U9Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'advanced', 'multiple_choice',
   '某商店同時賣出兩件商品，每件售價都是 240 元，其中一件賺了 20%，另一件虧了 20%，請問這家商店賣出這兩件商品總體是賺了還是虧了？',
   '["A. 賺了", "B. 不賺不虧", "C. 虧了", "D. 無法判斷"]'::jsonb,
   'C. 虧了',
   'p6_ax_2026', 'U9Q14a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'advanced', 'fill_in_number',
   '某商店同時賣出兩件商品，每件售價都是 240 元，其中一件賺了 20%，另一件虧了 20%，這家商店賣出這兩件商品總體虧了多少元？',
   NULL,
   '20',
   'p6_ax_2026', 'U9Q14b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'basic', 'fill_in_number',
   '解方程: 3(x+4)=27，x=？',
   NULL,
   '5',
   'p6_ax_2026', 'U10Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'basic', 'fill_in_number',
   '解方程: 2(2x-5)=14，x=？',
   NULL,
   '6',
   'p6_ax_2026', 'U10Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'fill_in_number',
   '解方程: 4x+2(x+3)=24，x=？',
   NULL,
   '3',
   'p6_ax_2026', 'U10Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'fill_in_number',
   '解方程: 10-3(x-2)=4，x=？',
   NULL,
   '4',
   'p6_ax_2026', 'U10Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'basic', 'fill_in_number',
   '解方程: 1.5x+2.5=10，x=？',
   NULL,
   '5',
   'p6_ax_2026', 'U10Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'fill_in_number',
   '解方程: 0.8(x-1.2)=3.2，x=？',
   NULL,
   '5.2',
   'p6_ax_2026', 'U10Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'fill_in_number',
   '解方程: 1/2 x + 1/3 x = 10，x=？',
   NULL,
   '12',
   'p6_ax_2026', 'U10Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'fill_in_number',
   '解方程: 3/4 x - 1/2 = 1，x=？',
   NULL,
   '2',
   'p6_ax_2026', 'U10Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'basic', 'fill_in_number',
   '列方程並求解：一個數的 3 倍加上 6 等於 21，這個數是多少？',
   NULL,
   '5',
   'p6_ax_2026', 'U10Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'basic', 'fill_in_number',
   '列方程並求解：一個數的 5 倍減去 8 等於 12，這個數是多少？',
   NULL,
   '4',
   'p6_ax_2026', 'U10Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'advanced', 'fill_in_number',
   '父親今年 40 歲，兒子今年 12 歲，多少年後父親的年齡是兒子的 3 倍？',
   NULL,
   '2',
   'p6_ax_2026', 'U10Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'fill_in_number',
   '果園裡蘋果樹和梨樹一共有 360 棵，蘋果樹的棵數是梨樹的 2 倍，梨樹有多少棵？',
   NULL,
   '120',
   'p6_ax_2026', 'U10Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'fill_in_number',
   '果園裡蘋果樹和梨樹一共有 360 棵，蘋果樹的棵數是梨樹的 2 倍，蘋果樹有多少棵？',
   NULL,
   '240',
   'p6_ax_2026', 'U10Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'advanced', 'fill_in_number',
   '甲、乙兩個工程隊共同修一條長 1200 米的公路，他們從兩端同時施工，15 天完成，甲隊每天修 45 米，乙隊每天修多少米？',
   NULL,
   '35',
   'p6_ax_2026', 'U10Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'advanced', 'fill_in_number',
   '學校買來 4 張桌子和 6 把椅子，一共用去 1080 元，每張桌子的價錢是每把椅子的 3 倍，每把椅子多少元？',
   NULL,
   '60',
   'p6_ax_2026', 'U10Q10a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'advanced', 'fill_in_number',
   '學校買來 4 張桌子和 6 把椅子，一共用去 1080 元，每張桌子的價錢是每把椅子的 3 倍，每張桌子多少元？',
   NULL,
   '180',
   'p6_ax_2026', 'U10Q10b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'fill_in_number',
   '解方程: 5x-12=3x+8，x=？',
   NULL,
   '10',
   'p6_ax_2026', 'U10Q11a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'fill_in_number',
   '解方程: 2(x+4)-3=17，x=？',
   NULL,
   '6',
   'p6_ax_2026', 'U10Q11b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'advanced', 'multiple_choice',
   '兩個連續偶數的和是 70，這兩個偶數分別是多少？',
   '["A. 32 和 38", "B. 33 和 37", "C. 34 和 36", "D. 36 和 38"]'::jsonb,
   'C. 34 和 36',
   'p6_ax_2026', 'U10Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'advanced', 'fill_in_number',
   '小明買了 3 支鋼筆和 2 本筆記本，一共花了 60 元，每支鋼筆比每本筆記本貴 5 元，每支鋼筆多少元？',
   NULL,
   '14',
   'p6_ax_2026', 'U10Q13a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'advanced', 'fill_in_number',
   '小明買了 3 支鋼筆和 2 本筆記本，一共花了 60 元，每支鋼筆比每本筆記本貴 5 元，每本筆記本多少元？',
   NULL,
   '9',
   'p6_ax_2026', 'U10Q13b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'basic', 'fill_in_number',
   '計算下列圓的面積（π 取 3.14）：半徑 r=4 厘米，面積是多少平方厘米？',
   NULL,
   '50.24',
   'p6_ax_2026', 'U11Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算下列圓的面積（π 取 3.14）：直徑 d=10 分米，面積是多少平方分米？',
   NULL,
   '78.5',
   'p6_ax_2026', 'U11Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算下列扇形的面積（π 取 3.14）：半徑 r=6 厘米，圓心角 n=90°，面積是多少平方厘米？',
   NULL,
   '28.26',
   'p6_ax_2026', 'U11Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算下列圓環的面積（π 取 3.14）：大圓半徑 R=5 厘米，小圓半徑 r=3 厘米，面積是多少平方厘米？',
   NULL,
   '50.24',
   'p6_ax_2026', 'U11Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算下列圓環的面積（π 取 3.14）：大圓直徑 D=12 分米，小圓直徑 d=8 分米，面積是多少平方分米？',
   NULL,
   '62.8',
   'p6_ax_2026', 'U11Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'advanced', 'fill_in_number',
   '一個圓形花壇的半徑是 5 米，在花壇周圍修一條 1 米寬的小路，這條小路的面積是多少平方米？（π 取 3.14）',
   NULL,
   '34.54',
   'p6_ax_2026', 'U11Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個圓的周長是 18.84 厘米，它的面積是多少平方厘米？（π 取 3.14）',
   NULL,
   '28.26',
   'p6_ax_2026', 'U11Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個半圓的直徑是 8 厘米，它的面積是多少平方厘米？（π 取 3.14）',
   NULL,
   '25.12',
   'p6_ax_2026', 'U11Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個正方形的邊長是 6 厘米，在正方形裡畫一個最大的圓，這個圓的面積是多少平方厘米？（π 取 3.14）',
   NULL,
   '28.26',
   'p6_ax_2026', 'U11Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'advanced', 'fill_in_number',
   '一個長方形長 10 厘米，闊 8 厘米，在長方形裡畫一個最大的圓，剩下的面積是多少平方厘米？（π 取 3.14）',
   NULL,
   '29.76',
   'p6_ax_2026', 'U11Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個圓形鐘錶的分針長 12 厘米，經過 1 小時，分針掃過的面積是多少平方厘米？（π 取 3.14）',
   NULL,
   '452.16',
   'p6_ax_2026', 'U11Q11a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個圓形鐘錶的分針長 12 厘米，經過 30 分鐘，分針掃過的面積是多少平方厘米？（π 取 3.14）',
   NULL,
   '226.08',
   'p6_ax_2026', 'U11Q11b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'multiple_choice',
   '一個正方體，用刀切一刀，截面不可能是下列哪個形狀？',
   '["A. 三角形", "B. 長方形", "C. 梯形", "D. 圓形"]'::jsonb,
   'D. 圓形',
   'p6_ax_2026', 'U11Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'basic', 'fill_in_number',
   '對於簡單多面體，頂點數 V、面數 F、棱數 E 滿足歐拉公式：V+F-E=2。一個正方體有 8 個頂點、6 個面，它有多少條棱？',
   NULL,
   '12',
   'p6_ax_2026', 'U11Q14', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'advanced', 'fill_in_number',
   '一個扇形的面積是 12.56 平方厘米，半徑是 4 厘米，請問這個扇形的圓心角是多少度？（π 取 3.14）',
   NULL,
   '90',
   'p6_ax_2026', 'U11Q15', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'basic', 'fill_in_number',
   '一輛汽車 3 小時行駛了 180 公里，這輛汽車的平均速率是多少 km/h？',
   NULL,
   '60',
   'p6_ax_2026', 'U12Q2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'basic', 'fill_in_number',
   '小明騎自行車的速率是 15km/h，他騎了 2.5 小時，一共行駛了多少公里？',
   NULL,
   '37.5',
   'p6_ax_2026', 'U12Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'basic', 'fill_in_number',
   '一列火車的平均速率是 120km/h，行駛 600 公里需要多少小時？',
   NULL,
   '5',
   'p6_ax_2026', 'U12Q4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '單位換算：72km/h = 多少 m/s？',
   NULL,
   '20',
   'p6_ax_2026', 'U12Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '單位換算：10m/s = 多少 km/h？',
   NULL,
   '36',
   'p6_ax_2026', 'U12Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '甲、乙兩地相距 300 公里，一輛汽車從甲地開往乙地，行了 4 小時後，距離乙地還有 20 公里，這輛汽車的平均速率是多少 km/h？',
   NULL,
   '70',
   'p6_ax_2026', 'U12Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '甲、乙兩人分別從相距 240 米的兩地同時出發，相向而行，甲的速率是 4m/s，乙的速率是 6m/s，多久後兩人相遇？(單位：秒)',
   NULL,
   '24',
   'p6_ax_2026', 'U12Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'advanced', 'fill_in_number',
   '甲、乙兩人在 400 米的環形跑道上跑步，甲的速率是 3m/s，乙的速率是 5m/s，兩人同時同地反向出發，多久後兩人第一次相遇？(單位：秒)',
   NULL,
   '50',
   'p6_ax_2026', 'U12Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'advanced', 'fill_in_number',
   '甲、乙兩人在 400 米的環形跑道上跑步，甲的速率是 3m/s，乙的速率是 5m/s，兩人同時同地同向出發，多久後乙第一次追上甲？(單位：秒)',
   NULL,
   '200',
   'p6_ax_2026', 'U12Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '甲、乙兩輛汽車分別從 A、B 兩地同時出發，相向而行，甲車的速率是 60km/h，乙車的速率是 80km/h，3 小時後兩車相遇，A、B 兩地相距多少公里？',
   NULL,
   '420',
   'p6_ax_2026', 'U12Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'advanced', 'fill_in_number',
   '一艘船在靜水中的速率是 15km/h，水流的速率是 3km/h，這艘船從甲地順流而下到乙地用了 4 小時，從乙地逆流返回甲地需要多少小時？',
   NULL,
   '6',
   'p6_ax_2026', 'U12Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'fill_in_number',
   '一個圓形圖中，某部分占總體的 25%，對應的圓心角是多少度？',
   NULL,
   '90',
   'p6_ax_2026', 'U13Q2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'fill_in_number',
   '一個圓形圖中，某個扇形的圓心角是 90 度，這個扇形占總體的百分之幾？(以百分數表示，只填數字)',
   NULL,
   '25',
   'p6_ax_2026', 'U13Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'fill_in_number',
   '六年級學生的放學出行方式統計中，坐巴士的占 40%，對應的圓心角是多少度？',
   NULL,
   '144',
   'p6_ax_2026', 'U13Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '六年級學生的放學出行方式統計中，坐巴士的占 40%，如果坐巴士的有 80 人，六年級一共有多少學生？',
   NULL,
   '200',
   'p6_ax_2026', 'U13Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '六年級一班學生最喜歡的運動項目圓形圖統計：籃球 30%，足球 25%，羽毛球 20%，乒乓球 15%，其他 10%。最喜歡籃球的人數對應的圓心角是多少度？',
   NULL,
   '108',
   'p6_ax_2026', 'U13Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '六年級一班學生最喜歡的運動項目圓形圖統計：籃球 30%，足球 25%，羽毛球 20%，乒乓球 15%，其他 10%。如果六年級一班有 40 名學生，最喜歡足球的有多少人？',
   NULL,
   '10',
   'p6_ax_2026', 'U13Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '六年級一班學生最喜歡的運動項目圓形圖統計：籃球 30%，足球 25%，羽毛球 20%，乒乓球 15%，其他 10%。羽毛球比乒乓球多的人數佔總人數的百分之幾？(只填數字)',
   NULL,
   '5',
   'p6_ax_2026', 'U13Q5c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個圓形圖展示了小明家一個月的開支情況，總開支是 8000 元，其中伙食費占 40%，房租占 25%，水電費占 10%，教育費占 15%，其他占 10%。小明家這個月的伙食費是多少元？',
   NULL,
   '3200',
   'p6_ax_2026', 'U13Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個圓形圖展示了小明家一個月的開支情況，總開支是 8000 元，其中伙食費占 40%，房租占 25%，水電費占 10%，教育費占 15%，其他占 10%。房租比水電費多多少元？',
   NULL,
   '1200',
   'p6_ax_2026', 'U13Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個圓形圖展示了小明家一個月的開支情況，其中教育費占 15%，教育費對應的圓心角是多少度？',
   NULL,
   '54',
   'p6_ax_2026', 'U13Q6c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '某學校六年級學生的數學考試成績圓形圖統計：優秀 35%，良好 45%，合格 15%，待合格 5%。如果待合格的有 10 人，六年級一共有多少學生？',
   NULL,
   '200',
   'p6_ax_2026', 'U13Q9a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '某學校六年級學生的數學考試成績圓形圖統計：優秀 35%，良好 45%，合格 15%，待合格 5%。如果待合格的有 10 人，優秀的有多少人？',
   NULL,
   '70',
   'p6_ax_2026', 'U13Q9b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'fill_in_number',
   '一個農場種植蔬菜的總面積是 20 公頃，其中黃瓜占 30%，番茄占 40%，茄子占 20%，剩下的種辣椒。種辣椒的面積占總面積的百分之幾？(只填數字)',
   NULL,
   '10',
   'p6_ax_2026', 'U13Q10a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個農場種植蔬菜的總面積是 20 公頃，其中黃瓜占 30%，番茄占 40%，種番茄的面積比種黃瓜的多多少公頃？',
   NULL,
   '2',
   'p6_ax_2026', 'U13Q10b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個圓形圖中，已知部分數量是 60，對應的圓心角是 120 度，請問總數是多少？',
   NULL,
   '180',
   'p6_ax_2026', 'U13Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '六年級學生參加興趣小組，美術組有 30 人，對應的圓心角是 72 度，請問六年級參加興趣小組的一共有多少人？',
   NULL,
   '150',
   'p6_ax_2026', 'U13Q13a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'advanced', 'fill_in_number',
   '六年級學生參加興趣小組，美術組有 30 人，對應的圓心角是 72 度，音樂組占總人數的 20%，音樂組有多少人？',
   NULL,
   '30',
   'p6_ax_2026', 'U13Q13b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'multiple_choice',
   '小明從一年級到六年級的身高變化：
| 年級 | 身高（厘米） |
| --- | --- |
| 一年級 | 120 |
| 二年級 | 125 |
| 三年級 | 130 |
| 四年級 | 138 |
| 五年級 | 145 |
| 六年級 | 152 |

從幾年級到幾年級身高增長最快？增長了多少厘米？',
   '["A. 三年級到四年級，增 8 厘米", "B. 四年級到五年級，增 7 厘米", "C. 一年級到二年級，增 5 厘米", "D. 五年級到六年級，增 7 厘米"]'::jsonb,
   'A. 三年級到四年級，增 8 厘米',
   'p6_ax_2026', 'U8Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'basic', 'fill_in_number',
   '小明從一年級到六年級的身高變化：
| 年級 | 身高（厘米） |
| --- | --- |
| 一年級 | 120 |
| 二年級 | 125 |
| 三年級 | 130 |
| 四年級 | 138 |
| 五年級 | 145 |
| 六年級 | 152 |

從一年級到六年級一共長高了多少厘米？',
   NULL,
   '32',
   'p6_ax_2026', 'U8Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'fill_in_number',
   '小明從一年級到六年級的身高變化：
| 年級 | 身高（厘米） |
| --- | --- |
| 一年級 | 120 |
| 二年級 | 125 |
| 三年級 | 130 |
| 四年級 | 138 |
| 五年級 | 145 |
| 六年級 | 152 |

小明平均每年長高多少厘米？',
   NULL,
   '6.4',
   'p6_ax_2026', 'U8Q4c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'fill_in_number',
   '某商店 2025 年上半年營業額：
| 月份 | 營業額（萬元） |
| --- | --- |
| 1月 | 20 |
| 2月 | 18 |
| 3月 | 25 |
| 4月 | 30 |
| 5月 | 28 |
| 6月 | 35 |

上半年平均每月的營業額是多少萬元？',
   NULL,
   '26',
   'p6_ax_2026', 'U8Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'multiple_choice',
   '某商店 2025 年上半年營業額：
| 月份 | 營業額（萬元） |
| --- | --- |
| 1月 | 20 |
| 2月 | 18 |
| 3月 | 25 |
| 4月 | 30 |
| 5月 | 28 |
| 6月 | 35 |

哪兩個月之間營業額增長最快？增長了多少萬元？',
   '["A. 1 月到 2 月，增 2 萬元", "B. 2 月到 3 月，增 7 萬元", "C. 3 月到 4 月，增 5 萬元", "D. 5 月到 6 月，增 7 萬元"]'::jsonb,
   'B. 2 月到 3 月，增 7 萬元',
   'p6_ax_2026', 'U8Q5c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'basic', 'multiple_choice',
   '要表示「五年級各班的人數」，選用棒形圖還是折線圖比較合適？',
   '["A. 棒形圖", "B. 折線圖", "C. 圓形圖", "D. 都可以"]'::jsonb,
   'A. 棒形圖',
   'p6_ax_2026', 'U8Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'basic', 'multiple_choice',
   '要表示「某病人一天內的體溫變化」，選用棒形圖還是折線圖比較合適？',
   '["A. 棒形圖", "B. 折線圖", "C. 圓形圖", "D. 都可以"]'::jsonb,
   'B. 折線圖',
   'p6_ax_2026', 'U8Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'basic', 'multiple_choice',
   '要表示「某公司上半年每月的銷量變化」，選用棒形圖還是折線圖比較合適？',
   '["A. 棒形圖", "B. 折線圖", "C. 圓形圖", "D. 都可以"]'::jsonb,
   'B. 折線圖',
   'p6_ax_2026', 'U8Q6c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'basic', 'multiple_choice',
   '要表示「學校各圖書室的圖書數量」，選用棒形圖還是折線圖比較合適？',
   '["A. 棒形圖", "B. 折線圖", "C. 圓形圖", "D. 都可以"]'::jsonb,
   'A. 棒形圖',
   'p6_ax_2026', 'U8Q6d', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=6 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'advanced', 'fill_in_number',
   '小明從家騎車去圖書館，再回家。
0-10 分鐘騎到 2 公里外的圖書館
在圖書館停留 20 分鐘
然後 10 分鐘騎車回家

小明全程的平均速率是多少 km/h？',
   NULL,
   '6',
   'p6_ax_2026', 'U8Q10', true);

COMMIT;

-- Sanity: SELECT count(*) FROM assessment_questions WHERE source_paper='p6_ax_2026' AND is_active;
-- Expect: 179