-- P4 assessment questions: 156 questions
-- Source: New assessment question and answer/P4 Ax Question.pdf + Answer.pdf
-- All reference the unit's placeholder topic (lesson_number = unit_number).
-- source_paper = 'p4_ax_2026'

BEGIN;

DELETE FROM assessment_questions WHERE source_paper = 'p4_ax_2026';

INSERT INTO assessment_questions
  (topic_id, difficulty_tier, question_type, question_text, options, correct_answer,
   source_paper, source_question, is_active)
VALUES
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'multiple_choice',
   '寫出 24 的所有因數。',
   '["A. 1、2、3、4、6、8、12、24", "B. 1、2、3、4、6、12、24", "C. 1、2、3、4、6、8、24", "D. 2、3、4、6、8、12、24"]'::jsonb,
   'A. 1、2、3、4、6、8、12、24',
   'p4_ax_2026', 'U1Q1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'multiple_choice',
   '下列哪些數既是 2 的倍數，也是 5 的倍數：18、25、40、57、80、95、100。',
   '["A. 25、95", "B. 40、80、100", "C. 18、57", "D. 18、40、80、100"]'::jsonb,
   'B. 40、80、100',
   'p4_ax_2026', 'U1Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'multiple_choice',
   '下列數字中，哪些是 3 的倍數：27、43、54、72、85、96、123。',
   '["A. 27、43、54、72、123", "B. 43、85、123", "C. 27、54、72、96、123", "D. 27、54、72、85、96"]'::jsonb,
   'C. 27、54、72、96、123',
   'p4_ax_2026', 'U1Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'basic', 'multiple_choice',
   '1-20 以內的所有質數有哪些？',
   '["A. 1、2、3、5、7、11、13、17、19", "B. 2、3、5、7、9、11、13、17、19", "C. 2、3、5、7、11、13、15、17、19", "D. 2、3、5、7、11、13、17、19"]'::jsonb,
   'D. 2、3、5、7、11、13、17、19',
   'p4_ax_2026', 'U1Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個兩位數，既是 2 的倍數，也是 3 的倍數，且十位數字是 5，這個兩位數是多少？',
   NULL,
   '54',
   'p4_ax_2026', 'U1Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'multiple_choice',
   '一個數既是 36 的因數，也是 6 的倍數，這個數可能是多少？（寫出所有可能）',
   '["A. 6、12、18、36", "B. 6、12、18", "C. 6、18、36", "D. 12、18、36"]'::jsonb,
   'A. 6、12、18、36',
   'p4_ax_2026', 'U1Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'advanced', 'multiple_choice',
   '一個 50 以下的兩位數是 4 的倍數，它的因數個數剛好是奇數，這個數可能是多少？',
   '["A. 16、24", "B. 16、36", "C. 16、25", "D. 36、64"]'::jsonb,
   'B. 16、36',
   'p4_ax_2026', 'U1Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=1 AND t.lesson_number=1 LIMIT 1), 'enhancement', 'multiple_choice',
   '三個連續偶數的和是 72，這三個偶數分別是多少？',
   '["A. 20、24、28", "B. 23、24、25", "C. 22、24、26", "D. 22、25、26"]'::jsonb,
   'C. 22、24、26',
   'p4_ax_2026', 'U1Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '12 和 18 的最大公因數（H.C.F.）是多少？',
   NULL,
   '6',
   'p4_ax_2026', 'U2Q1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '20 和 30 的 H.C.F. 是多少？',
   NULL,
   '10',
   'p4_ax_2026', 'U2Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '20 和 30 的 L.C.M. 是多少？',
   NULL,
   '60',
   'p4_ax_2026', 'U2Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '用短除法計算：16 和 24 的 H.C.F. 是多少？',
   NULL,
   '8',
   'p4_ax_2026', 'U2Q5_1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '16 和 24 的 L.C.M. 是多少？',
   NULL,
   '48',
   'p4_ax_2026', 'U2Q5_1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'basic', 'fill_in_number',
   '15 和 25 的 L.C.M. 是多少？',
   NULL,
   '75',
   'p4_ax_2026', 'U2Q5_2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'advanced', 'fill_in_number',
   '兩個數的 H.C.F. 是 4，L.C.M. 是 24，其中一個數是 8，另一個數是多少？',
   NULL,
   '12',
   'p4_ax_2026', 'U2Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'enhancement', 'fill_in_number',
   '把長 12 厘米、闊 9 厘米的長方形紙，剪成大小相同的正方形，且沒有剩餘，正方形的邊長最長是多少厘米？',
   NULL,
   '3',
   'p4_ax_2026', 'U2Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'advanced', 'fill_in_number',
   '將一堆糖果平分給 4 個、6 個或 9 個小朋友，每次都剛好剩下 2 粒，這堆糖果最少有多少粒？',
   NULL,
   '38',
   'p4_ax_2026', 'U2Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'advanced', 'fill_in_number',
   '兩個數的積是 180，它們的 H.C.F. 是 3，這兩個數的 L.C.M. 是多少？',
   NULL,
   '60',
   'p4_ax_2026', 'U2Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=2 AND t.lesson_number=2 LIMIT 1), 'enhancement', 'fill_in_number',
   '學校體育室有不到 50 個排球，3 個 3 個地數剛好數完，5 個 5 個地數也剛好數完，體育室最多有多少個排球？',
   NULL,
   '45',
   'p4_ax_2026', 'U2Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '計算：123 × 3 = ?',
   NULL,
   '369',
   'p4_ax_2026', 'U3Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '計算：214 × 20 = ?',
   NULL,
   '4280',
   'p4_ax_2026', 'U3Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '用豎式計算：132 × 23 = ?',
   NULL,
   '3036',
   'p4_ax_2026', 'U3Q2_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'basic', 'fill_in_number',
   '用豎式計算：245 × 36 = ?',
   NULL,
   '8820',
   'p4_ax_2026', 'U3Q2_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '用遞等式進行簡便計算：25 × 32 × 125 = ?',
   NULL,
   '100000',
   'p4_ax_2026', 'U3Q4_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '用遞等式進行簡便計算：102 × 45 = ?',
   NULL,
   '4590',
   'p4_ax_2026', 'U3Q4_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'enhancement', 'fill_in_number',
   '一盒牛奶售價 12 元，超市一天賣出 245 盒，一共收入多少元？',
   NULL,
   '2940',
   'p4_ax_2026', 'U3Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'advanced', 'fill_in_number',
   '小華在計算一道三位數乘兩位數的算式時，把兩位數 23 的個位 3 看成了 8，結果算出的積比正確的積多了 1250，正確的積是多少？',
   NULL,
   '5750',
   'p4_ax_2026', 'U3Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'advanced', 'fill_in_number',
   '文具店進行優惠活動，筆記本每本售價 8 元，「買 5 本送 2 本」。王老師要買 35 本筆記本，最少需要付多少元？',
   NULL,
   '200',
   'p4_ax_2026', 'U3Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=3 AND t.lesson_number=3 LIMIT 1), 'advanced', 'multiple_choice',
   '用 1、2、3、4、5 這五個數字組成一個三位數和一個兩位數，要使它們的乘積最大，這個算式是什麼？',
   '["A. 431 × 52", "B. 521 × 43", "C. 543 × 21", "D. 432 × 51"]'::jsonb,
   'A. 431 × 52',
   'p4_ax_2026', 'U3Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '計算：84 ÷ 21 = ?',
   NULL,
   '4',
   'p4_ax_2026', 'U4Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '計算：360 ÷ 40 = ?',
   NULL,
   '9',
   'p4_ax_2026', 'U4Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '用豎式計算：312 ÷ 24 = ?',
   NULL,
   '13',
   'p4_ax_2026', 'U4Q2_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '用豎式計算：528 ÷ 16 = ?',
   NULL,
   '33',
   'p4_ax_2026', 'U4Q2_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '計算：609 ÷ 3 = ?',
   NULL,
   '203',
   'p4_ax_2026', 'U4Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'basic', 'fill_in_number',
   '計算：840 ÷ 7 = ?',
   NULL,
   '120',
   'p4_ax_2026', 'U4Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'fill_in_number',
   '用商不變的性質進行簡便計算：4200 ÷ 25 = ?',
   NULL,
   '168',
   'p4_ax_2026', 'U4Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'fill_in_number',
   '水果店要把 230 個蘋果裝箱，每箱最多裝 15 個，最少需要多少個箱子？',
   NULL,
   '16',
   'p4_ax_2026', 'U4Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'fill_in_number',
   '小明有 50 元，記事本每本 12 元，他最多可以買多少本記事本？',
   NULL,
   '4',
   'p4_ax_2026', 'U4Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'advanced', 'fill_in_number',
   '小馬虎在計算一道除法算式時，把除數 24 看成了 42，結果得到的商是 8，餘數是 24，正確的商是多少？',
   NULL,
   '15',
   'p4_ax_2026', 'U4Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=4 AND t.lesson_number=4 LIMIT 1), 'enhancement', 'fill_in_number',
   '學校組織 320 名師生去郊遊，每輛旅遊巴最多可坐 45 人，最少需要租多少輛旅遊巴？',
   NULL,
   '8',
   'p4_ax_2026', 'U4Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '計算：36 + 64 ÷ 4 = ?',
   NULL,
   '52',
   'p4_ax_2026', 'U5Q1_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '計算：150 - 25 × 4 = ?',
   NULL,
   '50',
   'p4_ax_2026', 'U5Q1_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '用遞等式計算：240 ÷ 6 × 5 = ?',
   NULL,
   '200',
   'p4_ax_2026', 'U5Q2_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'enhancement', 'fill_in_number',
   '用遞等式計算：120 - 72 ÷ 8 + 29 = ?',
   NULL,
   '140',
   'p4_ax_2026', 'U5Q2_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'basic', 'fill_in_number',
   '計算含有括號的算式：(36 + 64) ÷ 4 = ?',
   NULL,
   '25',
   'p4_ax_2026', 'U5Q3_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算含有括號的算式：15 × (200 - 145) = ?',
   NULL,
   '825',
   'p4_ax_2026', 'U5Q3_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'enhancement', 'fill_in_number',
   '用遞等式進行簡便計算：63 × 99 + 63 = ?',
   NULL,
   '6300',
   'p4_ax_2026', 'U5Q4_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'enhancement', 'fill_in_number',
   '文具店賣出 12 盒鋼筆，每盒 6 支，一共收入 864 元，每支鋼筆售價多少元？',
   NULL,
   '12',
   'p4_ax_2026', 'U5Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'advanced', 'fill_in_number',
   '電器店進行優惠活動，電風扇每台售價 128 元，「買 4 台送 1 台」。公司買了 20 台電風扇，一共需要付多少元？',
   NULL,
   '2048',
   'p4_ax_2026', 'U5Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'enhancement', 'fill_in_number',
   '一輛汽車從甲地開往乙地，前 3 小時平均每小時行 65 千米，後 2 小時一共行了 140 千米，剛好到達乙地，甲乙兩地相距多少千米？',
   NULL,
   '335',
   'p4_ax_2026', 'U5Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=5 AND t.lesson_number=5 LIMIT 1), 'enhancement', 'fill_in_number',
   '學校圖書館買來 240 本故事書，比科技書的 2 倍少 40 本，學校買來科技書多少本？',
   NULL,
   '140',
   'p4_ax_2026', 'U5Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=7 AND t.lesson_number=7 LIMIT 1), 'enhancement', 'multiple_choice',
   '判斷下列說法：(1)不相交的兩條直線一定是平行線。(2)兩條直線相交成直角，這兩條直線互相垂直。(3)長方形的兩組對邊互相平行，相鄰的邊互相垂直。哪組答案正確？',
   '["A. ×、√、√", "B. √、√、√", "C. ×、×、√", "D. ×、√、×"]'::jsonb,
   'A. ×、√、√',
   'p4_ax_2026', 'U7Q1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=7 AND t.lesson_number=7 LIMIT 1), 'basic', 'fill_in_number',
   '正方形有幾組互相平行的邊？',
   NULL,
   '2',
   'p4_ax_2026', 'U7Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=7 AND t.lesson_number=7 LIMIT 1), 'basic', 'fill_in_number',
   '正方形有幾組互相垂直的邊？',
   NULL,
   '4',
   'p4_ax_2026', 'U7Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=7 AND t.lesson_number=7 LIMIT 1), 'enhancement', 'multiple_choice',
   '下面的字母中，A、E、F、H、M、N、Z，有互相平行的線段的字母有哪些？',
   '["A. A、E、F、H、M、N、Z", "B. E、F、H", "C. A、M、N、Z", "D. F、H、Z"]'::jsonb,
   'A. A、E、F、H、M、N、Z',
   'p4_ax_2026', 'U7Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=7 AND t.lesson_number=7 LIMIT 1), 'enhancement', 'fill_in_number',
   '同一平面內，畫與已知直線距離為 2 厘米的平行線，最多可以畫多少條？',
   NULL,
   '2',
   'p4_ax_2026', 'U7Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=7 AND t.lesson_number=7 LIMIT 1), 'enhancement', 'fill_in_number',
   '從家到公路有三條小路，長度分別是 120 米、150 米、90 米，其中一條小路與公路互相垂直，這條小路的長度是多少米？',
   NULL,
   '90',
   'p4_ax_2026', 'U7Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'basic', 'fill_in_number',
   '長方形有幾條邊？',
   NULL,
   '4',
   'p4_ax_2026', 'U8Q1_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'multiple_choice',
   '判斷：(1)正方形是特殊的長方形。(2)平行四邊形的四個角都是直角。(3)有一組對邊平行的四邊形，叫做梯形。(4)長方形和正方形都是特殊的平行四邊形。哪組答案正確？',
   '["A. √、×、×、√", "B. √、√、×、√", "C. ×、×、×、√", "D. √、×、√、√"]'::jsonb,
   'A. √、×、×、√',
   'p4_ax_2026', 'U8Q2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'basic', 'multiple_choice',
   '梯形有多少條高？',
   '["A. 1", "B. 無數", "C. 2", "D. 4"]'::jsonb,
   'B. 無數',
   'p4_ax_2026', 'U8Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'multiple_choice',
   '一個長方形的長是 8 厘米，闊是 5 厘米，如果把它的長減少 3 厘米，就變成了什麼圖形？',
   '["A. 長方形", "B. 平行四邊形", "C. 正方形", "D. 梯形"]'::jsonb,
   'C. 正方形',
   'p4_ax_2026', 'U8Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方形的長是 8 厘米，闊是 5 厘米，把它的長減少 3 厘米後，這個圖形的邊長是多少厘米？',
   NULL,
   '5',
   'p4_ax_2026', 'U8Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'multiple_choice',
   '用兩個完全相同的梯形，可以拼成一個什麼圖形？',
   '["A. 長方形", "B. 正方形", "C. 三角形", "D. 平行四邊形"]'::jsonb,
   'D. 平行四邊形',
   'p4_ax_2026', 'U8Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=8 AND t.lesson_number=8 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個等腰梯形的上底是 4 厘米，下底是 6 厘米，腰長是 5 厘米，它的周界是多少厘米？',
   NULL,
   '20',
   'p4_ax_2026', 'U8Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'basic', 'fill_in_number',
   '邊長為 6 厘米的正方形周界是多少厘米？',
   NULL,
   '24',
   'p4_ax_2026', 'U9Q2_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'basic', 'fill_in_number',
   '長 12 米、闊 8 米的長方形周界是多少米？',
   NULL,
   '40',
   'p4_ax_2026', 'U9Q2_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'basic', 'fill_in_number',
   '一個正方形的周界是 48 分米，它的邊長是多少分米？',
   NULL,
   '12',
   'p4_ax_2026', 'U9Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方形的周界是 40 厘米，長是 12 厘米，它的闊是多少厘米？',
   NULL,
   '8',
   'p4_ax_2026', 'U9Q4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '用一根長 36 厘米的鐵絲，圍成一個正方形，這個正方形的邊長是多少厘米？',
   NULL,
   '9',
   'p4_ax_2026', 'U9Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '用一根長 36 厘米的鐵絲圍成長方形，長是 10 厘米，闊是多少厘米？',
   NULL,
   '8',
   'p4_ax_2026', 'U9Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方形操場，長是 100 米，闊是 50 米，小明沿著操場跑了 2 圈，他一共跑了多少米？',
   NULL,
   '600',
   'p4_ax_2026', 'U9Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'advanced', 'fill_in_number',
   '一個正方形的周界和一個長方形的周界相等，長方形的長是 14 厘米，闊是 10 厘米，正方形的邊長是多少厘米？',
   NULL,
   '12',
   'p4_ax_2026', 'U9Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=9 AND t.lesson_number=9 LIMIT 1), 'advanced', 'fill_in_number',
   '從一個長 20 厘米、闊 12 厘米的長方形紙中，剪去一個最大的正方形，剩下的圖形的周界是多少厘米？',
   NULL,
   '40',
   'p4_ax_2026', 'U9Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'basic', 'multiple_choice',
   '把一個蛋糕平均分成 6 份，每份是這個蛋糕的幾分之幾？',
   '["A. 1/6", "B. 1/5", "C. 5/6", "D. 1/1"]'::jsonb,
   'A. 1/6',
   'p4_ax_2026', 'U10Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'basic', 'multiple_choice',
   '把一個蛋糕平均分成 6 份，5 份是這個蛋糕的幾分之幾？',
   '["A. 1/6", "B. 5/6", "C. 6/5", "D. 5/5"]'::jsonb,
   'B. 5/6',
   'p4_ax_2026', 'U10Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'multiple_choice',
   '下列分數中，哪些是真分數：1/3、5/4、6/6、7/9、12/5、2/2？',
   '["A. 5/4、12/5", "B. 6/6、2/2", "C. 1/3、7/9", "D. 1/3、6/6、7/9"]'::jsonb,
   'C. 1/3、7/9',
   'p4_ax_2026', 'U10Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'multiple_choice',
   '把 3 個披薩平分給 5 個小朋友，每人分得多少個披薩？',
   '["A. 5/3 個", "B. 1/5 個", "C. 3/15 個", "D. 3/5 個"]'::jsonb,
   'D. 3/5 個',
   'p4_ax_2026', 'U10Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'multiple_choice',
   '把 3 個披薩平分給 5 個小朋友，每人分得全部披薩的幾分之幾？',
   '["A. 1/5", "B. 3/5", "C. 1/3", "D. 1/15"]'::jsonb,
   'A. 1/5',
   'p4_ax_2026', 'U10Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'basic', 'fill_in_number',
   '2 裡面有多少個 1/3？',
   NULL,
   '6',
   'p4_ax_2026', 'U10Q9a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'basic', 'fill_in_number',
   '5/8 裡面有多少個 1/8？',
   NULL,
   '5',
   'p4_ax_2026', 'U10Q9b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'fill_in_number',
   '一條繩子長 12 米，剪下它的 1/4，剪下了多少米？',
   NULL,
   '3',
   'p4_ax_2026', 'U10Q11a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=10 AND t.lesson_number=10 LIMIT 1), 'enhancement', 'multiple_choice',
   '一條繩子長 12 米，剪下它的 1/4，還剩下全長的幾分之幾？',
   '["A. 1/4", "B. 3/4", "C. 1/3", "D. 1/8"]'::jsonb,
   'B. 3/4',
   'p4_ax_2026', 'U10Q11b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'basic', 'multiple_choice',
   '把 3/4 擴成分母是 24 的分數是多少？',
   '["A. 18/24", "B. 15/24", "C. 12/24", "D. 24/24"]'::jsonb,
   'A. 18/24',
   'p4_ax_2026', 'U11Q2_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'basic', 'fill_in_number',
   '8/12 的分子和分母的最大公因數（H.C.F.）是多少？',
   NULL,
   '4',
   'p4_ax_2026', 'U11Q3_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'basic', 'fill_in_number',
   '15/25 的分子和分母的最大公因數（H.C.F.）是多少？',
   NULL,
   '5',
   'p4_ax_2026', 'U11Q3_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'basic', 'fill_in_number',
   '24/36 的分子和分母的最大公因數（H.C.F.）是多少？',
   NULL,
   '12',
   'p4_ax_2026', 'U11Q3_3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'basic', 'multiple_choice',
   '把 10/15 約成最簡分數是多少？',
   '["A. 5/15", "B. 2/3", "C. 10/3", "D. 3/5"]'::jsonb,
   'B. 2/3',
   'p4_ax_2026', 'U11Q4_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'basic', 'multiple_choice',
   '把 18/24 約成最簡分數是多少？',
   '["A. 9/12", "B. 2/3", "C. 3/4", "D. 6/8"]'::jsonb,
   'C. 3/4',
   'p4_ax_2026', 'U11Q4_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'basic', 'multiple_choice',
   '把 35/49 約成最簡分數是多少？',
   '["A. 7/9", "B. 5/9", "C. 35/49", "D. 5/7"]'::jsonb,
   'D. 5/7',
   'p4_ax_2026', 'U11Q4_3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'advanced', 'fill_in_number',
   '一個分數是 12/16，如果把它的分子減去 9，要使分數的大小不變，分母應該減去多少？',
   NULL,
   '12',
   'p4_ax_2026', 'U11Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'multiple_choice',
   '小明看一本 80 頁的故事書，第一天看了 20 頁，第一天看了全書的幾分之幾？（約成最簡分數）',
   '["A. 1/4", "B. 20/80", "C. 1/5", "D. 2/8"]'::jsonb,
   'A. 1/4',
   'p4_ax_2026', 'U11Q11a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=11 AND t.lesson_number=11 LIMIT 1), 'enhancement', 'multiple_choice',
   '小明看一本 80 頁的故事書，第二天看了 30 頁，第二天看了全書的幾分之幾？（約成最簡分數）',
   '["A. 30/80", "B. 3/8", "C. 1/3", "D. 3/10"]'::jsonb,
   'B. 3/8',
   'p4_ax_2026', 'U11Q11b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'basic', 'fill_in_number',
   '計算：2/7 + 3/7 = ?',
   NULL,
   '5/7',
   'p4_ax_2026', 'U12Q1_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'basic', 'fill_in_number',
   '計算：8/9 - 5/9 = ?（結果約成最簡分數）',
   NULL,
   '1/3',
   'p4_ax_2026', 'U12Q1_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'basic', 'fill_in_number',
   '計算：5/12 + 3/12 = ?（結果約成最簡分數）',
   NULL,
   '2/3',
   'p4_ax_2026', 'U12Q2_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'basic', 'fill_in_number',
   '計算：11/15 - 4/15 = ?',
   NULL,
   '7/15',
   'p4_ax_2026', 'U12Q2_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'basic', 'fill_in_number',
   '計算：1 - 3/8 = ?',
   NULL,
   '5/8',
   'p4_ax_2026', 'U12Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算：2 1/5 + 3 2/5 = ?',
   NULL,
   '5 3/5',
   'p4_ax_2026', 'U12Q4_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算：4 3/7 - 1 2/7 = ?',
   NULL,
   '3 1/7',
   'p4_ax_2026', 'U12Q4_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '計算：3 - 1 1/4 = ?',
   NULL,
   '1 3/4',
   'p4_ax_2026', 'U12Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'advanced', 'fill_in_number',
   '計算：5 - 2 3/7 - 1 2/7 = ?',
   NULL,
   '1 2/7',
   'p4_ax_2026', 'U12Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '一根繩子長 7/10 米，第一次用去了 2/10 米，第二次用去了 3/10 米，還剩下多少米？（約成最簡分數）',
   NULL,
   '1/5',
   'p4_ax_2026', 'U12Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '一包大米，第一天吃了全部的 2/9，第二天吃了全部的 3/9，兩天一共吃了全部的幾分之幾？',
   NULL,
   '5/9',
   'p4_ax_2026', 'U12Q10a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'enhancement', 'fill_in_number',
   '一包大米，第一天吃了全部的 2/9，第二天吃了全部的 3/9，還剩下全部的幾分之幾？',
   NULL,
   '4/9',
   'p4_ax_2026', 'U12Q10b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=12 AND t.lesson_number=12 LIMIT 1), 'advanced', 'fill_in_number',
   '小華看一本書，第一天看了全書的 3/8，第二天比第一天多看了全書的 1/8，兩天一共看了全書的幾分之幾？',
   NULL,
   '7/8',
   'p4_ax_2026', 'U12Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'fill_in_number',
   '0.7 裡面有多少個 0.1？',
   NULL,
   '7',
   'p4_ax_2026', 'U13Q3_1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'fill_in_number',
   '0.05 裡面有多少個 0.01？',
   NULL,
   '5',
   'p4_ax_2026', 'U13Q3_1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '3 個 1、5 個 0.1 和 2 個 0.01 組成的數是多少？',
   NULL,
   '3.52',
   'p4_ax_2026', 'U13Q3_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'fill_in_number',
   '把 3/10 化成小數是多少？',
   NULL,
   '0.3',
   'p4_ax_2026', 'U13Q4_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'fill_in_number',
   '把 27/100 化成小數是多少？',
   NULL,
   '0.27',
   'p4_ax_2026', 'U13Q4_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'fill_in_number',
   '把 135/1000 化成小數是多少？',
   NULL,
   '0.135',
   'p4_ax_2026', 'U13Q4_3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'fill_in_number',
   '把 0.4 化成最簡分數是多少？',
   NULL,
   '2/5',
   'p4_ax_2026', 'U13Q5_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '把 0.08 化成最簡分數是多少？',
   NULL,
   '2/25',
   'p4_ax_2026', 'U13Q5_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '把 1.25 化成假分數是多少？',
   NULL,
   '5/4',
   'p4_ax_2026', 'U13Q5_3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'multiple_choice',
   '比較大小：(1) 0.6○0.59 (2) 1.25○1.3 (3) 0.48○0.480。哪組答案正確？',
   '["A. >、<、=", "B. <、<、=", "C. >、>、=", "D. >、<、<"]'::jsonb,
   'A. >、<、=',
   'p4_ax_2026', 'U13Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'basic', 'multiple_choice',
   '小明的身高是 1.45 米，小華的身高是 1.5 米，誰的身高更高？',
   '["A. 小華", "B. 小明", "C. 一樣高", "D. 無法判斷"]'::jsonb,
   'A. 小華',
   'p4_ax_2026', 'U13Q11a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=13 AND t.lesson_number=13 LIMIT 1), 'enhancement', 'fill_in_number',
   '小明的身高是 1.45 米，小華的身高是 1.5 米，小華比小明高多少米？',
   NULL,
   '0.05',
   'p4_ax_2026', 'U13Q11b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=14 AND t.lesson_number=14 LIMIT 1), 'enhancement', 'fill_in_number',
   '最少用多少個完全相同的小正方形，可以拼成一個大正方形？',
   NULL,
   '4',
   'p4_ax_2026', 'U14Q2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=14 AND t.lesson_number=14 LIMIT 1), 'basic', 'fill_in_number',
   '最少用多少個完全相同的等腰直角三角形，可以拼成一個正方形？',
   NULL,
   '2',
   'p4_ax_2026', 'U14Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=14 AND t.lesson_number=14 LIMIT 1), 'advanced', 'fill_in_number',
   '把一個梯形用一條直線分割成兩個圖形，有幾種不同的分法？',
   NULL,
   '4',
   'p4_ax_2026', 'U14Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=14 AND t.lesson_number=14 LIMIT 1), 'basic', 'fill_in_number',
   '七巧板由多少種不同的圖形組成？',
   NULL,
   '3',
   'p4_ax_2026', 'U14Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=14 AND t.lesson_number=14 LIMIT 1), 'basic', 'fill_in_number',
   '七巧板中有多少個三角形？',
   NULL,
   '5',
   'p4_ax_2026', 'U14Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=14 AND t.lesson_number=14 LIMIT 1), 'advanced', 'fill_in_number',
   '一個長方形的長是 12 厘米，闊是 8 厘米，把它分割成兩個完全相同的小長方形，每個小長方形的周界最多是多少厘米？',
   NULL,
   '32',
   'p4_ax_2026', 'U14Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=14 AND t.lesson_number=14 LIMIT 1), 'advanced', 'fill_in_number',
   '用 12 個邊長是 1 厘米的小正方形，可以拼成多少種不同的長方形？',
   NULL,
   '3',
   'p4_ax_2026', 'U14Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=15 AND t.lesson_number=15 LIMIT 1), 'enhancement', 'multiple_choice',
   '判斷：(1)沿著一條直線對摺後，兩邊能完全重合的圖形，叫做軸對稱圖形。(2)所有的三角形都是軸對稱圖形。(3)長方形有 4 條對稱軸。哪組答案正確？',
   '["A. √、×、×", "B. √、√、√", "C. ×、×、√", "D. √、×、√"]'::jsonb,
   'A. √、×、×',
   'p4_ax_2026', 'U15Q1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=15 AND t.lesson_number=15 LIMIT 1), 'basic', 'fill_in_number',
   '正方形有多少條對稱軸？',
   NULL,
   '4',
   'p4_ax_2026', 'U15Q3_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=15 AND t.lesson_number=15 LIMIT 1), 'basic', 'fill_in_number',
   '長方形有多少條對稱軸？',
   NULL,
   '2',
   'p4_ax_2026', 'U15Q3_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=15 AND t.lesson_number=15 LIMIT 1), 'basic', 'fill_in_number',
   '等邊三角形有多少條對稱軸？',
   NULL,
   '3',
   'p4_ax_2026', 'U15Q3_3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=15 AND t.lesson_number=15 LIMIT 1), 'basic', 'multiple_choice',
   '軸對稱圖形中，對稱軸兩側的對應點到對稱軸的距離怎樣？',
   '["A. 不等", "B. 相等", "C. 一倍", "D. 一半"]'::jsonb,
   'B. 相等',
   'p4_ax_2026', 'U15Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=15 AND t.lesson_number=15 LIMIT 1), 'enhancement', 'multiple_choice',
   '下面的字母中，A、B、C、D、E、F、G、H、M、N、S、Z，哪些是軸對稱圖形？',
   '["A. A、B、C、D、E、F、G、H", "B. N、S、Z", "C. A、B、C、D、E、H、M", "D. A、E、F、H、M、N、Z"]'::jsonb,
   'C. A、B、C、D、E、H、M',
   'p4_ax_2026', 'U15Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=15 AND t.lesson_number=15 LIMIT 1), 'advanced', 'fill_in_number',
   '一個圖形沿著一條直線對摺後，直線右側的圖形是一個長 3 厘米、闊 2 厘米的長方形，這個完整的軸對稱圖形的面積最少是多少平方厘米？',
   NULL,
   '12',
   'p4_ax_2026', 'U15Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=15 AND t.lesson_number=15 LIMIT 1), 'advanced', 'fill_in_number',
   '鏡子裡的時鐘顯示的時間是 3 時，實際的時間是多少時？',
   NULL,
   '9',
   'p4_ax_2026', 'U15Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=16 AND t.lesson_number=16 LIMIT 1), 'enhancement', 'multiple_choice',
   '邊長是 1 厘米的正方形，面積是多少？',
   '["A. 1 平方厘米", "B. 2 平方厘米", "C. 1 平方米", "D. 4 平方厘米"]'::jsonb,
   'A. 1 平方厘米',
   'p4_ax_2026', 'U16Q1_3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=16 AND t.lesson_number=16 LIMIT 1), 'basic', 'fill_in_number',
   '邊長為 7 厘米的正方形面積是多少平方厘米？',
   NULL,
   '49',
   'p4_ax_2026', 'U16Q2_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=16 AND t.lesson_number=16 LIMIT 1), 'basic', 'fill_in_number',
   '長 15 米、闊 6 米的長方形面積是多少平方米？',
   NULL,
   '90',
   'p4_ax_2026', 'U16Q2_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=16 AND t.lesson_number=16 LIMIT 1), 'basic', 'fill_in_number',
   '一個長方形的面積是 96 平方分米，長是 12 分米，它的闊是多少分米？',
   NULL,
   '8',
   'p4_ax_2026', 'U16Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=16 AND t.lesson_number=16 LIMIT 1), 'basic', 'fill_in_number',
   '一個正方形的面積是 81 平方米，它的邊長是多少米？',
   NULL,
   '9',
   'p4_ax_2026', 'U16Q4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=16 AND t.lesson_number=16 LIMIT 1), 'advanced', 'fill_in_number',
   '一個房間長 6 米，闊 4 米，要用邊長 20 厘米的正方形地磚鋪滿，最少需要多少塊地磚？',
   NULL,
   '600',
   'p4_ax_2026', 'U16Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=16 AND t.lesson_number=16 LIMIT 1), 'advanced', 'fill_in_number',
   '從一個長 20 厘米、闊 15 厘米的長方形卡紙中，剪去一個最大的正方形，剩下的圖形的面積是多少平方厘米？',
   NULL,
   '75',
   'p4_ax_2026', 'U16Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=16 AND t.lesson_number=16 LIMIT 1), 'advanced', 'fill_in_number',
   '一個長方形的周界是 40 厘米，長比闊多 4 厘米，這個長方形的面積是多少平方厘米？',
   NULL,
   '96',
   'p4_ax_2026', 'U16Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=16 AND t.lesson_number=16 LIMIT 1), 'advanced', 'fill_in_number',
   '用一根長 36 厘米的鐵絲圍成一個長方形，怎樣圍才能使面積最大？最大的面積是多少平方厘米？',
   NULL,
   '81',
   'p4_ax_2026', 'U16Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=17 AND t.lesson_number=17 LIMIT 1), 'basic', 'multiple_choice',
   '四年級一班同學最喜歡水果統計：蘋果 12 人、香蕉 8 人、橙 10 人、西瓜 15 人、提子 5 人。最喜歡哪種水果的人數最多？有多少人？',
   '["A. 西瓜，15 人", "B. 蘋果，12 人", "C. 橙，10 人", "D. 香蕉，8 人"]'::jsonb,
   'A. 西瓜，15 人',
   'p4_ax_2026', 'U17Q2_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=17 AND t.lesson_number=17 LIMIT 1), 'basic', 'fill_in_number',
   '四年級一班同學最喜歡水果統計：蘋果 12 人、香蕉 8 人。最喜歡蘋果的人數比最喜歡香蕉的多多少人？',
   NULL,
   '4',
   'p4_ax_2026', 'U17Q2_3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=17 AND t.lesson_number=17 LIMIT 1), 'basic', 'fill_in_number',
   '四年級一班最喜歡水果統計：蘋果 12 人、香蕉 8 人、橙 10 人、西瓜 15 人、提子 5 人。四年級一班一共有多少人？',
   NULL,
   '50',
   'p4_ax_2026', 'U17Q2_4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=17 AND t.lesson_number=17 LIMIT 1), 'enhancement', 'fill_in_number',
   '最喜歡水果統計：蘋果 12 人、香蕉 8 人、橙 10 人、西瓜 15 人、提子 5 人。最喜歡西瓜的人數是最喜歡提子的多少倍？',
   NULL,
   '3',
   'p4_ax_2026', 'U17Q3_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=17 AND t.lesson_number=17 LIMIT 1), 'enhancement', 'fill_in_number',
   '某超市一周飲料銷量：周一20、周二15、周三17、周四22、周五30、周六45、周日40 箱。周末兩天一共銷售了多少箱飲料？',
   NULL,
   '85',
   'p4_ax_2026', 'U17Q4_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=17 AND t.lesson_number=17 LIMIT 1), 'enhancement', 'fill_in_number',
   '某超市一周飲料銷量：周一20、周二15、周三17、周四22、周五30、周六45、周日40 箱。平均每天銷售多少箱飲料？',
   NULL,
   '27',
   'p4_ax_2026', 'U17Q4_3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=17 AND t.lesson_number=17 LIMIT 1), 'advanced', 'fill_in_number',
   '一個棒形圖中，用 2 厘米長的柱子代表 10 人，那麼代表 35 人的柱子應該畫多少厘米長？',
   NULL,
   '7',
   'p4_ax_2026', 'U17Q7a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=17 AND t.lesson_number=17 LIMIT 1), 'advanced', 'fill_in_number',
   '一個棒形圖中，用 2 厘米長的柱子代表 10 人，那麼 5 厘米長的柱子代表多少人？',
   NULL,
   '25',
   'p4_ax_2026', 'U17Q7b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=18 AND t.lesson_number=18 LIMIT 1), 'enhancement', 'multiple_choice',
   '四年級一班和二班體育達標統計：一班優秀 15、良好 20、合格 10、待合格 2；二班優秀 18、良好 16、合格 12、待合格 1。哪個班的優秀人數更多？多多少人？',
   '["A. 二班，多 3 人", "B. 一班，多 3 人", "C. 二班，多 2 人", "D. 一班，多 2 人"]'::jsonb,
   'A. 二班，多 3 人',
   'p4_ax_2026', 'U18Q2_1', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=18 AND t.lesson_number=18 LIMIT 1), 'basic', 'fill_in_number',
   '一班良好 20 人，二班良好 16 人。兩個班良好等級的一共有多少人？',
   NULL,
   '36',
   'p4_ax_2026', 'U18Q2_3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=18 AND t.lesson_number=18 LIMIT 1), 'basic', 'fill_in_number',
   '一班：優秀 15、良好 20、合格 10、待合格 2。四年級一班一共有多少人？',
   NULL,
   '47',
   'p4_ax_2026', 'U18Q2_4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=18 AND t.lesson_number=18 LIMIT 1), 'enhancement', 'fill_in_number',
   '一班優秀 15、良好 20、合格 10、待合格 2；二班優秀 18、良好 16、合格 12、待合格 1。良好等級的人數相差多少人？',
   NULL,
   '4',
   'p4_ax_2026', 'U18Q3_2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=18 AND t.lesson_number=18 LIMIT 1), 'enhancement', 'fill_in_number',
   '上半年電視銷量：1月80、2月75、3月60、4月50、5月45、6月65 台。上半年電視一共銷售了多少台？',
   NULL,
   '375',
   'p4_ax_2026', 'U18Q4_2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=18 AND t.lesson_number=18 LIMIT 1), 'enhancement', 'fill_in_number',
   '上半年冰箱銷量：1月40、2月35、3月30、4月45、5月60、6月70 台。上半年冰箱一共銷售了多少台？',
   NULL,
   '280',
   'p4_ax_2026', 'U18Q4_2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=4 AND u.unit_number=18 AND t.lesson_number=18 LIMIT 1), 'advanced', 'multiple_choice',
   '電視：1月80、2月70、3月60、4月50、5月45、6月65 台；冰箱：1月40、2月35、3月30、4月45、5月60、6月70 台。哪個月電視和冰箱的銷量相差最大？相差多少台？',
   '["A. 1月，相差 40 台", "B. 6月，相差 5 台", "C. 3月，相差 30 台", "D. 2月，相差 40 台"]'::jsonb,
   'A. 1月，相差 40 台',
   'p4_ax_2026', 'U18Q4_3', true);

COMMIT;

-- Sanity: SELECT count(*) FROM assessment_questions WHERE source_paper='p4_ax_2026' AND is_active;
-- Expect: 156