-- P5 學前評估題庫 — migrated from hardcoded src/data/assessmentQuestions.ts
-- Source: 5 P5 enrollment-month papers (sept/nov/jan/mar/may), deduped to 60 unique questions.
-- 8 速率 (rate/speed) questions excluded as they are P6-syllabus, not P5.
--
-- Run AFTER seed_p5_curriculum.sql.
-- Idempotent: clears P5 manual_seed rows before re-insert.

BEGIN;

DELETE FROM assessment_questions
  WHERE source_paper IN ('p5_hardcoded_sept','p5_hardcoded_nov','p5_hardcoded_jan',
                          'p5_hardcoded_mar','p5_hardcoded_may');

-- Topic lookup: grade-qualified subquery, since P3 + P5 share lesson_numbers.
-- Pattern: (SELECT t.id FROM curriculum_topics t JOIN curriculum_units u
--           ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=N)

INSERT INTO assessment_questions
  (topic_id, question_text, question_type, options, correct_answer,
   difficulty_tier, source_paper, source_question, notes)
VALUES
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=21),
 '3.45 + 2.78 = ?',
 'multiple_choice', '["A. 5.23", "B. 6.13", "C. 6.23", "D. 7.23"]'::jsonb,
 'C. 6.23', 'basic',
 'p5_hardcoded_sept', 'CSV row 1', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=21),
 '10.5 - 3.78 = ?',
 'multiple_choice', '["A. 6.72", "B. 7.28", "C. 6.27", "D. 7.72"]'::jsonb,
 'A. 6.72', 'basic',
 'p5_hardcoded_sept', 'CSV row 2', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=23),
 '2.5 × 4 = ?',
 'multiple_choice', '["A. 10", "B. 8.5", "C. 2.5", "D. 100"]'::jsonb,
 'A. 10', 'basic',
 'p5_hardcoded_sept', 'CSV row 3', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=26),
 '8.4 ÷ 0.4 = ?',
 'multiple_choice', '["A. 2.1", "B. 21", "C. 210", "D. 0.21"]'::jsonb,
 'B. 21', 'basic',
 'p5_hardcoded_sept', 'CSV row 4', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=27),
 '下列哪個數最大？',
 'multiple_choice', '["A. 3.45", "B. 3.4", "C. 3.54", "D. 3.44"]'::jsonb,
 'C. 3.54', 'basic',
 'p5_hardcoded_sept', 'CSV row 5', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=21),
 '1.25小時 = ___ 分鐘',
 'multiple_choice', '["A. 60", "B. 75", "C. 80", "D. 125"]'::jsonb,
 'B. 75', 'basic',
 'p5_hardcoded_sept', 'CSV row 6', 'unit conversion 1.25hr'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=21),
 '6.5 + 6.7 = ___',
 'fill_in_number', NULL,
 '13.2', 'basic',
 'p5_hardcoded_sept', 'CSV row 7', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=21),
 '9.35 - 1.8 = ___',
 'fill_in_number', NULL,
 '7.55', 'basic',
 'p5_hardcoded_sept', 'CSV row 8', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=23),
 '0.45 × 20 = ___',
 'fill_in_number', NULL,
 '9', 'basic',
 'p5_hardcoded_sept', 'CSV row 9', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=26),
 '3.6 ÷ 0.4 = ___',
 'fill_in_number', NULL,
 '9', 'basic',
 'p5_hardcoded_sept', 'CSV row 10', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=27),
 '4.1 ___ 4.09（填入 >、< 或 =）',
 'fill_in', NULL,
 '>', 'basic',
 'p5_hardcoded_sept', 'CSV row 11', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=21),
 '2.5升 = ___ 毫升',
 'fill_in_number', NULL,
 '2500', 'basic',
 'p5_hardcoded_sept', 'CSV row 12', 'unit conv L/mL'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=4),
 '2/5 + 1/4 = ?',
 'multiple_choice', '["A. 3/9", "B. 13/20", "C. 3/20", "D. 1/5"]'::jsonb,
 'B. 13/20', 'basic',
 'p5_hardcoded_nov', 'CSV row 13', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=4),
 '5/6 - 1/3 = ?',
 'multiple_choice', '["A. 4/3", "B. 1/2", "C. 2/3", "D. 4/9"]'::jsonb,
 'B. 1/2', 'basic',
 'p5_hardcoded_nov', 'CSV row 14', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=28),
 '3/4 ÷ 1/2 = ?',
 'multiple_choice', '["A. 3/8", "B. 3/2", "C. 1/2", "D. 2/3"]'::jsonb,
 'B. 3/2', 'basic',
 'p5_hardcoded_nov', 'CSV row 15', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=15),
 '三角形的底是8cm，高是5cm，面積是多少？',
 'multiple_choice', '["A. 40cm²", "B. 20cm²", "C. 13cm²", "D. 80cm²"]'::jsonb,
 'B. 20cm²', 'basic',
 'p5_hardcoded_nov', 'CSV row 17', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=4),
 '1/2 + 1/3 = ___',
 'fill_in_number', NULL,
 '5/6', 'basic',
 'p5_hardcoded_nov', 'CSV row 19', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=4),
 '1/4 + 3/8 = ___',
 'fill_in_number', NULL,
 '5/8', 'basic',
 'p5_hardcoded_nov', 'CSV row 20', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=4),
 '7/10 - 2/5 = ___',
 'fill_in_number', NULL,
 '3/10', 'basic',
 'p5_hardcoded_nov', 'CSV row 21', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=6),
 '一個班有120人，其中4/5的學生完成了作業，完成作業的有多少人？',
 'fill_in_number', NULL,
 '96', 'enhancement',
 'p5_hardcoded_nov', 'CSV row 22', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=15),
 '三角形的底是20cm，高是18cm，面積是___cm²',
 'fill_in_number', NULL,
 '180', 'basic',
 'p5_hardcoded_nov', 'CSV row 23', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=3),
 '2/3 ___ 3/4（填入 >、< 或 =）',
 'fill_in', NULL,
 '<', 'basic',
 'p5_hardcoded_nov', 'CSV row 24', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=27),
 '3.45和3.450哪個較大？',
 'multiple_choice', '["A. 3.45較大", "B. 3.450較大", "C. 一樣大", "D. 無法比較"]'::jsonb,
 'C. 一樣大', 'basic',
 'p5_hardcoded_jan', 'CSV row 25', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=15),
 '三角形面積的計算公式是？',
 'multiple_choice', '["A. 底 × 高", "B. 底 × 高 ÷ 2", "C. 底 + 高", "D. 底 × 高 × 2"]'::jsonb,
 'B. 底 × 高 ÷ 2', 'basic',
 'p5_hardcoded_jan', 'CSV row 27', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=15),
 '長方形長8cm、寬5cm，面積是多少？',
 'multiple_choice', '["A. 26cm²", "B. 26cm", "C. 40cm²", "D. 80cm²"]'::jsonb,
 'C. 40cm²', 'basic',
 'p5_hardcoded_jan', 'CSV row 28', 'rectangle area, P4 prereq'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=26),
 '2.5 ÷ 0.05 = ?',
 'multiple_choice', '["A. 5", "B. 50", "C. 500", "D. 0.05"]'::jsonb,
 'B. 50', 'basic',
 'p5_hardcoded_jan', 'CSV row 30', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=15),
 '正方形面積25cm²，它的邊長是___cm',
 'fill_in_number', NULL,
 '5', 'basic',
 'p5_hardcoded_jan', 'CSV row 33', 'square reverse area'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=21),
 '4.5 - 2.5 = ___',
 'fill_in_number', NULL,
 '2', 'basic',
 'p5_hardcoded_jan', 'CSV row 34', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=33),
 '$500加20%是多少？',
 'multiple_choice', '["A. $520", "B. $600", "C. $550", "D. $620"]'::jsonb,
 'B. $600', 'enhancement',
 'p5_hardcoded_mar', 'CSV row 37', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=17),
 '5³ = ?',
 'multiple_choice', '["A. 15", "B. 125", "C. 50", "D. 555"]'::jsonb,
 'B. 125', 'basic',
 'p5_hardcoded_mar', 'CSV row 38', '5^3 cube'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=37),
 '四次測驗的分數分別是80、90、85、85，平均分是多少？',
 'multiple_choice', '["A. 85分", "B. 84分", "C. 86分", "D. 87分"]'::jsonb,
 'A. 85分', 'basic',
 'p5_hardcoded_mar', 'CSV row 39', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=33),
 '某商品打八折後售價$320，原價是多少？',
 'multiple_choice', '["A. $400", "B. $360", "C. $380", "D. $420"]'::jsonb,
 'A. $400', 'enhancement',
 'p5_hardcoded_mar', 'CSV row 40', 'reverse 八折'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=17),
 '長方體長10cm、寬8cm、高5cm，體積是多少？',
 'multiple_choice', '["A. 400cm³", "B. 300cm³", "C. 450cm³", "D. 500cm³"]'::jsonb,
 'A. 400cm³', 'basic',
 'p5_hardcoded_mar', 'CSV row 41', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=33),
 '一班40人，其中35%喜歡數學，有多少人喜歡數學？',
 'multiple_choice', '["A. 14人", "B. 16人", "C. 12人", "D. 18人"]'::jsonb,
 'A. 14人', 'basic',
 'p5_hardcoded_mar', 'CSV row 42', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=33),
 '$100加20%是$___',
 'fill_in_number', NULL,
 '120', 'basic',
 'p5_hardcoded_mar', 'CSV row 43', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=17),
 '6³ = ___',
 'fill_in_number', NULL,
 '216', 'basic',
 'p5_hardcoded_mar', 'CSV row 44', '6^3'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=37),
 '兩次測驗的分數分別是80分和95分，平均分是___分',
 'fill_in_number', NULL,
 '87.5', 'basic',
 'p5_hardcoded_mar', 'CSV row 45', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=17),
 '長方體長9cm、寬7cm、高4cm，體積是___cm³',
 'fill_in_number', NULL,
 '252', 'basic',
 'p5_hardcoded_mar', 'CSV row 46', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=15),
 '正方形邊長20cm，面積是___cm²',
 'fill_in_number', NULL,
 '400', 'basic',
 'p5_hardcoded_mar', 'CSV row 47', 'square area'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=33),
 '一班40人，其中60%的學生喜歡運動，有___人喜歡運動',
 'fill_in_number', NULL,
 '24', 'basic',
 'p5_hardcoded_mar', 'CSV row 48', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=33),
 '某商品原價$600，打七折再減$50，現價是多少？',
 'multiple_choice', '["A. $370", "B. $350", "C. $400", "D. $420"]'::jsonb,
 'A. $370', 'enhancement',
 'p5_hardcoded_may', 'CSV row 49', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=31),
 '3 : 5 = x : 40，x = ?',
 'multiple_choice', '["A. 18", "B. 24", "C. 30", "D. 15"]'::jsonb,
 'B. 24', 'basic',
 'p5_hardcoded_may', 'CSV row 50', 'ratio/proportion'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=36),
 '一個水壺容量1500mL，每杯250mL，可以倒多少杯？',
 'multiple_choice', '["A. 5杯", "B. 6杯", "C. 7杯", "D. 8杯"]'::jsonb,
 'B. 6杯', 'basic',
 'p5_hardcoded_may', 'CSV row 51', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=33),
 '成本$200，售價$250，利潤率是多少？',
 'multiple_choice', '["A. 20%", "B. 25%", "C. 50%", "D. 80%"]'::jsonb,
 'B. 25%', 'enhancement',
 'p5_hardcoded_may', 'CSV row 52', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=13),
 '2x + 8 = 24，x = ?',
 'multiple_choice', '["A. 4", "B. 8", "C. 16", "D. 6"]'::jsonb,
 'B. 8', 'enhancement',
 'p5_hardcoded_may', 'CSV row 53', '2-step equation'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=36),
 '一個長方形水缸長80cm、寬50cm、高40cm，容量是多少升？',
 'multiple_choice', '["A. 160升", "B. 16升", "C. 1600升", "D. 0.16升"]'::jsonb,
 'A. 160升', 'enhancement',
 'p5_hardcoded_may', 'CSV row 54', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=33),
 '原價$900，打八折，售價$___',
 'fill_in_number', NULL,
 '720', 'basic',
 'p5_hardcoded_may', 'CSV row 55', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=31),
 'a : b = 4 : 5，a = 20，b = ___',
 'fill_in_number', NULL,
 '25', 'basic',
 'p5_hardcoded_may', 'CSV row 56', 'ratio basic'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=12),
 'x - 15 = 20，x = ___',
 'fill_in_number', NULL,
 '35', 'basic',
 'p5_hardcoded_may', 'CSV row 57', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=13),
 '5x - 2 = 63，x = ___',
 'fill_in_number', NULL,
 '13', 'enhancement',
 'p5_hardcoded_may', 'CSV row 58', '2-step eq'),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=17),
 '長方形水缸長80cm、寬50cm、高18cm，容量是___cm³',
 'fill_in_number', NULL,
 '72000', 'basic',
 'p5_hardcoded_may', 'CSV row 59', NULL),
((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND t.lesson_number=36),
 '一個圓柱形容器底面積500cm²、高7cm，容積是___cm³',
 'fill_in_number', NULL,
 '3500', 'enhancement',
 'p5_hardcoded_may', 'CSV row 60', '底×高 vol');

COMMIT;

-- Sanity:
-- SELECT count(*), difficulty_tier FROM assessment_questions q
--   JOIN curriculum_topics t ON t.id = q.topic_id
--   JOIN curriculum_units u ON u.id = t.unit_id
--   WHERE u.grade = 5 AND q.is_active GROUP BY 2;

-- Skipped (not migrated, not in P5 syllabus):
--   row 16: 速率 = P6 content
--   row 18: 速率 = P6 content
--   row 26: 速率 = P6 content
--   row 29: 速率 = P6 content
--   row 31: 速率 = P6 content
--   row 32: 速率 = P6 content
--   row 35: 速率 = P6 content
--   row 36: 速率 = P6 content
