-- P5 brand-new question pool — REUSES existing curriculum_units (names match exactly).
-- Old P5 questions are DEACTIVATED (not deleted) per user request.
-- 231 new questions across 19 units.

BEGIN;

-- 1. Update U17 name (existing: '長方體和正方體的體積'; new: '長方體和正方體的表面積與體積')
UPDATE curriculum_units SET name = '長方體和正方體的表面積與體積'
  WHERE grade = 5 AND unit_number = 17;

-- 2. Deactivate old P5 questions (preserve in DB for history)
UPDATE assessment_questions SET is_active = false
WHERE source_paper IN (
  'p5_hardcoded_sept', 'p5_hardcoded_nov', 'p5_hardcoded_jan',
  '五年級期末複習手冊', 'p5_image_questions'
) AND is_active = true;

-- 3. Clear any prior runs of this seed
DELETE FROM assessment_questions WHERE source_paper = 'p5_ax_2026';

INSERT INTO assessment_questions
  (topic_id, difficulty_tier, question_type, question_text, options, correct_answer,
   source_paper, source_question, is_active)
VALUES
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '寫出數字 3500000 的讀法。',
   '["A. 三十五萬", "B. 三百五十萬", "C. 三千五百萬", "D. 三千五百"]'::jsonb,
   'B. 三百五十萬',
   'p5_ax_2026', 'U1Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把「七百二十萬」寫成阿拉伯數字。',
   NULL,
   '7200000',
   'p5_ax_2026', 'U1Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '把「三千零五萬零四百」寫成阿拉伯數字。',
   NULL,
   '30050400',
   'p5_ax_2026', 'U1Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '用四捨五入法把 346890 捨入至萬位。',
   NULL,
   '350000',
   'p5_ax_2026', 'U1Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '用四捨五入法把 1295000 捨入至萬位。',
   NULL,
   '1300000',
   'p5_ax_2026', 'U1Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個數用四捨五入法捨入至萬位是 50 萬，這個數最大是多少？',
   NULL,
   '504999',
   'p5_ax_2026', 'U1Q7max', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個數用四捨五入法捨入至萬位是 50 萬，這個數最小是多少？',
   NULL,
   '495000',
   'p5_ax_2026', 'U1Q7min', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '香港某屋苑的樓價是 8950000 元，用四捨五入法捨入至十萬位，約是多少元？',
   NULL,
   '9000000',
   'p5_ax_2026', 'U1Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '超市一年的營業額是 12489000 元，其中線上營業額佔 3500000 元，剩下的線下營業額是多少元？',
   NULL,
   '8989000',
   'p5_ax_2026', 'U1Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '估算下列算式的結果：49800 + 30200 ≈ ？',
   NULL,
   '80000',
   'p5_ax_2026', 'U1Q11a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=1 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '估算下列算式的結果：120500 - 49800 ≈ ？',
   NULL,
   '70000',
   'p5_ax_2026', 'U1Q11b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '用短除法求 6 和 9 的最小公倍數（L.C.M.）。',
   NULL,
   '18',
   'p5_ax_2026', 'U2Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '用短除法求 8 和 12 的最小公倍數（L.C.M.）。',
   NULL,
   '24',
   'p5_ax_2026', 'U2Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '比較分數大小，3/4 ○ 5/8，○ 內應填？',
   '["A. >", "B. <", "C. =", "D. 無法比較"]'::jsonb,
   'A. >',
   'p5_ax_2026', 'U2Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '比較分數大小，2/5 ○ 3/7，○ 內應填？',
   '["A. >", "B. <", "C. =", "D. 無法比較"]'::jsonb,
   'B. <',
   'p5_ax_2026', 'U2Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算下列算式，結果約成最簡分數：1/2 + 1/3 = ？',
   NULL,
   '5/6',
   'p5_ax_2026', 'U2Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算下列算式，結果約成最簡分數：5/6 - 1/4 = ？',
   NULL,
   '7/12',
   'p5_ax_2026', 'U2Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算下列算式，結果約成最簡分數：3/4 + 5/8 - 1/2 = ？',
   NULL,
   '7/8',
   'p5_ax_2026', 'U2Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算下列算式，結果約成最簡分數：11/12 - 1/3 + 1/6 = ？',
   NULL,
   '3/4',
   'p5_ax_2026', 'U2Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算帶分數加法：2 1/4 + 3 2/3 = ？',
   NULL,
   '5 11/12',
   'p5_ax_2026', 'U2Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算帶分數減法：5 3/5 - 2 1/2 = ？',
   NULL,
   '3 1/10',
   'p5_ax_2026', 'U2Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '計算：10 - 3 1/4 - 2 2/3 = ？',
   NULL,
   '4 1/12',
   'p5_ax_2026', 'U2Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一根繩子長 5 米，第一次剪去 1 1/2 米，第二次剪去 2 1/3 米，還剩下多少米？',
   NULL,
   '1 1/6',
   'p5_ax_2026', 'U2Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '小明看一本書，第一天看了全書的 1/4，第二天看了全書的 2/5，兩天一共看了全書的幾分之幾？',
   NULL,
   '13/20',
   'p5_ax_2026', 'U2Q11a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=2 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '小明看一本書，第一天看了全書的 1/4，第二天看了全書的 2/5，還剩下全書的幾分之幾沒看？',
   NULL,
   '7/20',
   'p5_ax_2026', 'U2Q11b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算，結果約成最簡分數：3 × 2/5 = ？',
   NULL,
   '6/5',
   'p5_ax_2026', 'U3Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算，結果約成最簡分數：4/9 × 6 = ？',
   NULL,
   '8/3',
   'p5_ax_2026', 'U3Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算，結果約成最簡分數：2/3 × 3/4 = ？',
   NULL,
   '1/2',
   'p5_ax_2026', 'U3Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算，結果約成最簡分數：5/6 × 8/15 = ？',
   NULL,
   '4/9',
   'p5_ax_2026', 'U3Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算帶分數乘法，結果約成最簡分數：1 1/2 × 2/3 = ？',
   NULL,
   '1',
   'p5_ax_2026', 'U3Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算帶分數乘法，結果約成最簡分數：2 2/5 × 1 1/4 = ？',
   NULL,
   '3',
   'p5_ax_2026', 'U3Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '用遞等式進行簡便計算：2/5 × 3/7 × 5 = ？',
   NULL,
   '6/7',
   'p5_ax_2026', 'U3Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '用遞等式進行簡便計算：(1/4 + 2/3) × 12 = ？',
   NULL,
   '11',
   'p5_ax_2026', 'U3Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一箱蘋果有 24 個，其中 3/4 是紅蘋果，紅蘋果有多少個？',
   NULL,
   '18',
   'p5_ax_2026', 'U3Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '香港某中學有學生 1500 人，其中五年級學生佔總人數的 1/5，五年級女生佔五年級總人數的 2/5，五年級女生有多少人？',
   NULL,
   '120',
   'p5_ax_2026', 'U3Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一塊長方形的菜地，長是 12 米，闊是長的 3/4，這塊菜地的面積是多少平方米？',
   NULL,
   '108',
   'p5_ax_2026', 'U3Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '一根鋼管長 6 米，第一次用去全長的 1/3，第二次用去剩下的 1/2，兩次一共用去多少米？',
   NULL,
   '4',
   'p5_ax_2026', 'U3Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=3 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '小明的體重是 45 克，爸爸的體重比小明重 2/3，爸爸的體重是多少克？',
   NULL,
   '75',
   'p5_ax_2026', 'U3Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '寫出 a × 3 的規範寫法。',
   '["A. a3", "B. 3a", "C. a+3", "D. a×3"]'::jsonb,
   'B. 3a',
   'p5_ax_2026', 'U4Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '寫出 x ÷ 4 的規範寫法。',
   '["A. x4", "B. 4x", "C. x/4", "D. 4/x"]'::jsonb,
   'C. x/4',
   'p5_ax_2026', 'U4Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '省略乘號，寫出 5 × y 的式子。',
   '["A. y5", "B. 5y", "C. 5+y", "D. y/5"]'::jsonb,
   'B. 5y',
   'p5_ax_2026', 'U4Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '省略乘號，寫出 t × t 的式子。',
   '["A. 2t", "B. t+t", "C. t²", "D. t/t"]'::jsonb,
   'C. t²',
   'p5_ax_2026', 'U4Q2c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '用代數式表示「比 x 大 5 的數」。',
   '["A. 5x", "B. x-5", "C. x+5", "D. 5-x"]'::jsonb,
   'C. x+5',
   'p5_ax_2026', 'U4Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '用代數式表示「y 的 3 倍」。',
   '["A. y+3", "B. y-3", "C. y/3", "D. 3y"]'::jsonb,
   'D. 3y',
   'p5_ax_2026', 'U4Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '用代數式表示「15 減去 b 的差」。',
   '["A. b-15", "B. 15-b", "C. 15+b", "D. 15b"]'::jsonb,
   'B. 15-b',
   'p5_ax_2026', 'U4Q4c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '當 x=5, y=3 時，計算 2x + 4y 的值。',
   NULL,
   '22',
   'p5_ax_2026', 'U4Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '當 x=5, y=3 時，計算 x² - y² 的值。',
   NULL,
   '16',
   'p5_ax_2026', 'U4Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一本故事書有 120 頁，小明每天看 a 頁，看了 5 天，當 a=15 時，還剩下多少頁沒看？',
   NULL,
   '45',
   'p5_ax_2026', 'U4Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=4 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '甲有 x 元，乙的錢是甲的 2 倍少 10 元，當 x=50 時，乙有多少元？',
   NULL,
   '90',
   'p5_ax_2026', 'U4Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '解方程：x + 12 = 25，x = ？',
   NULL,
   '13',
   'p5_ax_2026', 'U5Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '解方程：y - 18 = 32，y = ？',
   NULL,
   '50',
   'p5_ax_2026', 'U5Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '解方程：5x = 45，x = ？',
   NULL,
   '9',
   'p5_ax_2026', 'U5Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '解方程：x ÷ 6 = 12，x = ？',
   NULL,
   '72',
   'p5_ax_2026', 'U5Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '解方程：15 - x = 7，x = ？',
   NULL,
   '8',
   'p5_ax_2026', 'U5Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '解方程：24 ÷ y = 4，y = ？',
   NULL,
   '6',
   'p5_ax_2026', 'U5Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '列方程解應用題：一個數加上 15 等於 42，這個數是多少？',
   NULL,
   '27',
   'p5_ax_2026', 'U5Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方形的面積是 96 平方米，長是 12 米，闊是 x 米，求闊。',
   NULL,
   '8',
   'p5_ax_2026', 'U5Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '水果店運來一批蘋果，賣了 45 公斤，還剩 38 公斤，這批蘋果一共有 x 公斤，求 x。',
   NULL,
   '83',
   'p5_ax_2026', 'U5Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '小明有 80 張郵票，是小華的 2 倍，小華有 x 張郵票，求 x。',
   NULL,
   '40',
   'p5_ax_2026', 'U5Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個數的 5 倍減去 8 等於 22，這個數是多少？（列方程求解）',
   NULL,
   '6',
   'p5_ax_2026', 'U5Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=5 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '學校圖書館買來 200 本故事書，比科技書的 3 倍少 10 本，科技書有 x 本，求 x。',
   NULL,
   '70',
   'p5_ax_2026', 'U5Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=6 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '東北的相反方向是？',
   '["A. 西北", "B. 東南", "C. 西南", "D. 西"]'::jsonb,
   'C. 西南',
   'p5_ax_2026', 'U6Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=6 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '西南的相反方向是？',
   '["A. 東南", "B. 西北", "C. 東北", "D. 東"]'::jsonb,
   'C. 東北',
   'p5_ax_2026', 'U6Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=6 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '西北的相反方向是？',
   '["A. 東北", "B. 東南", "C. 西南", "D. 北"]'::jsonb,
   'B. 東南',
   'p5_ax_2026', 'U6Q2c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=6 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '東南的相反方向是？',
   '["A. 西南", "B. 東北", "C. 西北", "D. 西"]'::jsonb,
   'C. 西北',
   'p5_ax_2026', 'U6Q2d', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=6 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '小明家在學校的東南面，學校在小明家的什麼面？',
   '["A. 東南", "B. 西北", "C. 西南", "D. 東北"]'::jsonb,
   'B. 西北',
   'p5_ax_2026', 'U6Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=6 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '公園在商場的西北面，商場在公園的什麼面？',
   '["A. 西北", "B. 東南", "C. 西南", "D. 東北"]'::jsonb,
   'B. 東南',
   'p5_ax_2026', 'U6Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=6 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'multiple_choice',
   '從起點出發，先向東走 50 米，再向南走 50 米，現在的位置在起點的什麼面？',
   '["A. 東北", "B. 西南", "C. 東南", "D. 西北"]'::jsonb,
   'C. 東南',
   'p5_ax_2026', 'U6Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=6 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'multiple_choice',
   '從起點出發，先向西走 30 米，再向北走 30 米，現在的位置在起點的什麼面？',
   '["A. 東北", "B. 西南", "C. 東南", "D. 西北"]'::jsonb,
   'D. 西北',
   'p5_ax_2026', 'U6Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=6 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '小明從家出發，向西北走了 100 米到達超市，買完東西後，他要沿原路回家，應該向什麼方向走？',
   '["A. 西北", "B. 西南", "C. 東南", "D. 東北"]'::jsonb,
   'C. 東南',
   'p5_ax_2026', 'U6Q10dir', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=6 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '小明從家出發，向西北走了 100 米到達超市，沿原路回家要走多少米？',
   NULL,
   '100',
   'p5_ax_2026', 'U6Q10dist', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算平行四邊形的面積：底是 12 厘米，高是 8 厘米。（單位：平方厘米）',
   NULL,
   '96',
   'p5_ax_2026', 'U7Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算三角形的面積：底是 15 厘米，高是 6 厘米。（單位：平方厘米）',
   NULL,
   '45',
   'p5_ax_2026', 'U7Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算梯形的面積：上底是 5 米，下底是 9 米，高是 4 米。（單位：平方米）',
   NULL,
   '28',
   'p5_ax_2026', 'U7Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個平行四邊形的面積是 72 平方分米，底是 9 分米，它的高是多少分米？',
   NULL,
   '8',
   'p5_ax_2026', 'U7Q4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個三角形的面積是 45 平方厘米，高是 10 厘米，它的底是多少厘米？',
   NULL,
   '9',
   'p5_ax_2026', 'U7Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個梯形的面積是 80 平方米，上底是 7 米，下底是 13 米，它的高是多少米？',
   NULL,
   '8',
   'p5_ax_2026', 'U7Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '在一個底為 20 厘米、高為 15 厘米的平行四邊形內，畫一個最大的三角形，這個三角形的面積是多少平方厘米？',
   NULL,
   '150',
   'p5_ax_2026', 'U7Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '一塊梯形的菜地，上底是 12 米，下底是 18 米，高是 10 米，如果每平方米種 5 棵白菜，這塊菜地一共可以種多少棵白菜？',
   NULL,
   '750',
   'p5_ax_2026', 'U7Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '一塊三角形的廣告牌，底是 8 米，高是 6 米，現在要給廣告牌的兩面刷油漆，每平方米需要油漆 0.5 公斤，一共需要多少公斤油漆？',
   NULL,
   '24',
   'p5_ax_2026', 'U7Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個平行四邊形和一個三角形的面積相等，底也相等，平行四邊形的高是 6 厘米，三角形的高是多少厘米？',
   NULL,
   '12',
   'p5_ax_2026', 'U7Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=7 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '一個梯形的上底是 6 厘米，如果把上底延長 4 厘米，就變成了一個面積是 120 平方厘米的平行四邊形，原來梯形的面積是多少平方厘米？',
   NULL,
   '96',
   'p5_ax_2026', 'U7Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算長方體的體積：長 8 厘米，闊 5 厘米，高 4 厘米。（單位：立方厘米）',
   NULL,
   '160',
   'p5_ax_2026', 'U8Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算正方體的體積：棱長是 6 厘米。（單位：立方厘米）',
   NULL,
   '216',
   'p5_ax_2026', 'U8Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '單位換算：5 立方米 = ？ 立方分米',
   NULL,
   '5000',
   'p5_ax_2026', 'U8Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '單位換算：3600 立方厘米 = ？ 立方分米',
   NULL,
   '3.6',
   'p5_ax_2026', 'U8Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體的體積是 240 立方厘米，長是 8 厘米，闊是 5 厘米，它的高是多少厘米？',
   NULL,
   '6',
   'p5_ax_2026', 'U8Q4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個正方體的體積是 125 立方米，它的棱長是多少米？',
   NULL,
   '5',
   'p5_ax_2026', 'U8Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體魚缸，長 60 厘米，闊 40 厘米，高 30 厘米，這個魚缸最多能裝多少升水？（1 升 = 1000 立方厘米）',
   NULL,
   '72',
   'p5_ax_2026', 'U8Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '把一個棱長為 10 厘米的大正方體，切成棱長為 2 厘米的小正方體，一共可以切成多少個小正方體？',
   NULL,
   '125',
   'p5_ax_2026', 'U8Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一個長方體的游泳池，長 50 米，闊 25 米，深 2 米，這個游泳池的容積是多少立方米？',
   NULL,
   '2500',
   'p5_ax_2026', 'U8Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '用一根長 72 厘米的鐵絲，焊接成一個正方體框架，這個正方體的體積是多少立方厘米？',
   NULL,
   '216',
   'p5_ax_2026', 'U8Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=8 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體的木料，長 2 米，橫截面是一個邊長為 5 厘米的正方形，這根木料的體積是多少立方厘米？',
   NULL,
   '5000',
   'p5_ax_2026', 'U8Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '五年級一班男生 22 人女生 20 人，二班男生 24 人女生 18 人。哪個班的男生人數更多？',
   '["A. 一班", "B. 二班", "C. 一樣多", "D. 無法判斷"]'::jsonb,
   'B. 二班',
   'p5_ax_2026', 'U9Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '五年級一班男生 22 人女生 20 人，二班男生 24 人女生 18 人。兩個班一共有多少人？',
   NULL,
   '84',
   'p5_ax_2026', 'U9Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '五年級一班男生 22 人女生 20 人，二班男生 24 人女生 18 人。一班的總人數比二班多多少人？',
   NULL,
   '0',
   'p5_ax_2026', 'U9Q2c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'multiple_choice',
   '上半年牛奶銷量為 1 月 120 箱、2 月 100 箱、3 月 90 箱、4 月 80 箱、5 月 110 箱、6 月 130 箱；酸奶為 80、90、100、120、110、140 箱。哪個月牛奶和酸奶的銷量相差最大？',
   '["A. 1 月", "B. 2 月", "C. 4 月", "D. 6 月"]'::jsonb,
   'A. 1 月',
   'p5_ax_2026', 'U9Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '上半年牛奶銷量為 1 月 120 箱、2 月 100 箱、3 月 90 箱、4 月 80 箱、5 月 110 箱、6 月 130 箱。上半年牛奶一共銷售多少箱？',
   NULL,
   '630',
   'p5_ax_2026', 'U9Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '上半年酸奶銷量為 1 月 80、2 月 90、3 月 100、4 月 120、5 月 110、6 月 140 箱。上半年酸奶一共銷售多少箱？',
   NULL,
   '640',
   'p5_ax_2026', 'U9Q3c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '在複合棒形圖中，用 2 厘米長的柱子代表 50 人，那麼代表 125 人的柱子應該畫多少厘米長？',
   NULL,
   '5',
   'p5_ax_2026', 'U9Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '在複合棒形圖中，用 2 厘米長的柱子代表 50 人，那麼 6 厘米長的柱子代表多少人？',
   NULL,
   '150',
   'p5_ax_2026', 'U9Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '分店 A 1月 80 萬、2月 100 萬、3月 120 萬元；分店 B 1月 90 萬、2月 110 萬、3月 100 萬元。分店 A 哪個月的營業額最高？',
   '["A. 1 月", "B. 2 月", "C. 3 月", "D. 一樣"]'::jsonb,
   'C. 3 月',
   'p5_ax_2026', 'U9Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '分店 A 1月 80 萬、2月 100 萬、3月 120 萬元；分店 B 1月 90 萬、2月 110 萬、3月 100 萬元。第一季度分店 A 的總營業額是多少萬元？',
   NULL,
   '300',
   'p5_ax_2026', 'U9Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=9 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'multiple_choice',
   '分店 A 1月 80 萬、2月 100 萬、3月 120 萬元；分店 B 1月 90 萬、2月 110 萬、3月 100 萬元。兩個分店哪個月的營業額相差最小？',
   '["A. 1 月", "B. 2 月", "C. 3 月", "D. 都一樣"]'::jsonb,
   'A. 1 月',
   'p5_ax_2026', 'U9Q8c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算：3.2 + 1.5 = ？',
   NULL,
   '4.7',
   'p5_ax_2026', 'U10Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算：7.8 - 2.3 = ？',
   NULL,
   '5.5',
   'p5_ax_2026', 'U10Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '用豎式計算：12.45 + 3.6 = ？',
   NULL,
   '16.05',
   'p5_ax_2026', 'U10Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '用豎式計算：20 - 5.78 = ？',
   NULL,
   '14.22',
   'p5_ax_2026', 'U10Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '簡便計算：5.6 + 3.7 + 4.4 = ？',
   NULL,
   '13.7',
   'p5_ax_2026', 'U10Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '簡便計算：15.8 - 2.4 - 7.6 = ？',
   NULL,
   '5.8',
   'p5_ax_2026', 'U10Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算：12.5 + 4.8 - 3.2 = ？',
   NULL,
   '14.1',
   'p5_ax_2026', 'U10Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算：20 - (8.5 + 3.2) = ？',
   NULL,
   '8.3',
   'p5_ax_2026', 'U10Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一本數學書售價 45.8 元，一本語文書售價 38.5 元，兩本書一共多少元？',
   NULL,
   '84.3',
   'p5_ax_2026', 'U10Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一本數學書售價 45.8 元，一本語文書售價 38.5 元，數學書比語文書貴多少元？',
   NULL,
   '7.3',
   'p5_ax_2026', 'U10Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '小明的身高是 1.45 米，小華比小明高 0.12 米，小強比小華矮 0.08 米，小強的身高是多少米？',
   NULL,
   '1.49',
   'p5_ax_2026', 'U10Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一條繩子長 10 米，第一次剪去 3.25 米，第二次剪去 4.5 米，還剩下多少米？',
   NULL,
   '2.25',
   'p5_ax_2026', 'U10Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '超市優惠活動，一包大米原價 88.5 元，現在售價 79.9 元，便宜了多少元？',
   NULL,
   '8.6',
   'p5_ax_2026', 'U10Q11a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一包大米現在售價 79.9 元，媽媽買了兩包，一共花了多少元？',
   NULL,
   '159.8',
   'p5_ax_2026', 'U10Q11b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=10 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '三個數的和是 15.6，其中兩個數分別是 3.8 和 5.2，第三個數是多少？',
   NULL,
   '6.6',
   'p5_ax_2026', 'U10Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算：0.3 × 4 = ？',
   NULL,
   '1.2',
   'p5_ax_2026', 'U11Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算：2.5 × 0.4 = ？',
   NULL,
   '1',
   'p5_ax_2026', 'U11Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '用豎式計算：1.25 × 3.6 = ？',
   NULL,
   '4.5',
   'p5_ax_2026', 'U11Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '用豎式計算：0.48 × 2.5 = ？',
   NULL,
   '1.2',
   'p5_ax_2026', 'U11Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '用遞等式進行簡便計算：0.25 × 3.7 × 4 = ？',
   NULL,
   '3.7',
   'p5_ax_2026', 'U11Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '用遞等式進行簡便計算：1.2 × 9.9 + 1.2 × 0.1 = ？',
   NULL,
   '12',
   'p5_ax_2026', 'U11Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '蘋果每公斤售價 12.5 元，買 3.5 公斤需要多少元？',
   NULL,
   '43.75',
   'p5_ax_2026', 'U11Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一個長方形的長是 3.6 米，闊是 2.5 米，它的面積是多少平方米？',
   NULL,
   '9',
   'p5_ax_2026', 'U11Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '香港 1 港元可以兌換人民幣 0.92 元，1000 港元可以兌換多少人民幣？',
   NULL,
   '920',
   'p5_ax_2026', 'U11Q9a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一輛汽車每小時行駛 80.5 米，從甲地到乙地行駛了 2.5 小時，甲乙兩地相距多少米？',
   NULL,
   '201.25',
   'p5_ax_2026', 'U11Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '用簡便方法計算：10.1 × 4.5 = ？',
   NULL,
   '45.45',
   'p5_ax_2026', 'U11Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一個正方形的邊長是 2.4 厘米，它的周界是多少厘米？',
   NULL,
   '9.6',
   'p5_ax_2026', 'U11Q13a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=11 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一個正方形的邊長是 2.4 厘米，它的面積是多少平方厘米？',
   NULL,
   '5.76',
   'p5_ax_2026', 'U11Q13b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算：4.8 ÷ 2 = ？',
   NULL,
   '2.4',
   'p5_ax_2026', 'U12Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算：7.2 ÷ 0.9 = ？',
   NULL,
   '8',
   'p5_ax_2026', 'U12Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '用豎式計算：15.6 ÷ 12 = ？',
   NULL,
   '1.3',
   'p5_ax_2026', 'U12Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '用豎式計算：1.44 ÷ 1.2 = ？',
   NULL,
   '1.2',
   'p5_ax_2026', 'U12Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '用商不變的性質進行簡便計算：3.6 ÷ 0.25 = ？',
   NULL,
   '14.4',
   'p5_ax_2026', 'U12Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把 3.5 克的糖果平均分給 5 個小朋友，每個小朋友分得多少克？',
   NULL,
   '0.7',
   'p5_ax_2026', 'U12Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一輛汽車行駛 120 米耗油 9.6 升，平均每米耗油多少升？',
   NULL,
   '0.08',
   'p5_ax_2026', 'U12Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一輛汽車行駛 120 米耗油 9.6 升，平均每升油可以行駛多少米？',
   NULL,
   '12.5',
   'p5_ax_2026', 'U12Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '香港計程車首 2 米收費 27 元，之後每 0.2 米收費 1.9 元，李叔叔坐計程車付了 60.8 元，他最多坐了多少米？',
   NULL,
   '5.6',
   'p5_ax_2026', 'U12Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '用四捨五入法求商的近似值（保留一位小數）：10 ÷ 3 ≈ ？',
   NULL,
   '3.3',
   'p5_ax_2026', 'U12Q10a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '用四捨五入法求商的近似值（保留兩位小數）：5.6 ÷ 2.1 ≈ ？',
   NULL,
   '2.67',
   'p5_ax_2026', 'U12Q10b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一個長方形的面積是 12.6 平方米，長是 4.5 米，它的闊是多少米？',
   NULL,
   '2.8',
   'p5_ax_2026', 'U12Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '小馬虎在計算一道除法算式時，把除數 2.4 看成了 4.2，結果得到的商是 1.6，正確的商是多少？',
   NULL,
   '2.8',
   'p5_ax_2026', 'U12Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=12 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '做一個玩具需要 0.8 米的布料，現在有 25 米的布料，最多可以做多少個這樣的玩具？',
   NULL,
   '31',
   'p5_ax_2026', 'U12Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把分數 3/10 化成小數。',
   NULL,
   '0.3',
   'p5_ax_2026', 'U13Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把分數 27/100 化成小數。',
   NULL,
   '0.27',
   'p5_ax_2026', 'U13Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把分數 3/4 化成小數。',
   NULL,
   '0.75',
   'p5_ax_2026', 'U13Q1c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把分數 5/8 化成小數。',
   NULL,
   '0.625',
   'p5_ax_2026', 'U13Q1d', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把小數 0.6 化成最簡分數。',
   NULL,
   '3/5',
   'p5_ax_2026', 'U13Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把小數 0.25 化成最簡分數。',
   NULL,
   '1/4',
   'p5_ax_2026', 'U13Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '把小數 1.75 化成最簡假分數。',
   NULL,
   '7/4',
   'p5_ax_2026', 'U13Q2c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把小數 0.04 化成最簡分數。',
   NULL,
   '1/25',
   'p5_ax_2026', 'U13Q2d', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算 3/4 + 0.25，先化成小數，結果為？',
   NULL,
   '1',
   'p5_ax_2026', 'U13Q7a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算 1.5 - 1/2，先化成小數，結果為？',
   NULL,
   '1',
   'p5_ax_2026', 'U13Q7b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算，結果化為最簡分數：0.2 × 3/5 = ？',
   NULL,
   '3/25',
   'p5_ax_2026', 'U13Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算，結果化為最簡分數：4/5 ÷ 0.8 = ？',
   NULL,
   '1',
   'p5_ax_2026', 'U13Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '把循環小數 0.333…… 化成分數。',
   NULL,
   '1/3',
   'p5_ax_2026', 'U13Q10a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '把循環小數 0.1666…… 化成分數。',
   NULL,
   '1/6',
   'p5_ax_2026', 'U13Q10b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '小明看一本書，第一天看了全書的 2/5，第二天看了全書的 0.3，兩天一共看了全書的幾分之幾？',
   NULL,
   '7/10',
   'p5_ax_2026', 'U13Q11a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=13 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '小明看一本書，第一天看了 2/5，第二天看了 0.3，還剩下全書的幾分之幾沒看？',
   NULL,
   '3/10',
   'p5_ax_2026', 'U13Q11b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '寫出 3/4 的倒數。',
   NULL,
   '4/3',
   'p5_ax_2026', 'U14Q1a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '寫出 5 的倒數。',
   NULL,
   '1/5',
   'p5_ax_2026', 'U14Q1b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '寫出 1 2/3 的倒數。',
   NULL,
   '3/5',
   'p5_ax_2026', 'U14Q1c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算，結果約成最簡分數：3/4 ÷ 2 = ？',
   NULL,
   '3/8',
   'p5_ax_2026', 'U14Q2a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算，結果約成最簡分數：6 ÷ 2/3 = ？',
   NULL,
   '9',
   'p5_ax_2026', 'U14Q2b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算，結果約成最簡分數：4/5 ÷ 2/3 = ？',
   NULL,
   '6/5',
   'p5_ax_2026', 'U14Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算，結果約成最簡分數：8/9 ÷ 4/15 = ？',
   NULL,
   '10/3',
   'p5_ax_2026', 'U14Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算帶分數除法，結果約成最簡分數：1 1/2 ÷ 3/4 = ？',
   NULL,
   '2',
   'p5_ax_2026', 'U14Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算帶分數除法，結果約成最簡分數：2 2/5 ÷ 1 1/5 = ？',
   NULL,
   '2',
   'p5_ax_2026', 'U14Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一根繩子長 6 米，每 2/3 米剪一段，可以剪成多少段？',
   NULL,
   '9',
   'p5_ax_2026', 'U14Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一輛汽車 3/4 小時行駛了 60 米，平均每小時行駛多少米？',
   NULL,
   '80',
   'p5_ax_2026', 'U14Q9', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '小明 2/3 小時做了 12 道數學題，平均每小時做多少道題？',
   NULL,
   '18',
   'p5_ax_2026', 'U14Q10a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '小明 2/3 小時做了 12 道數學題，做一道題需要多少小時？',
   NULL,
   '1/18',
   'p5_ax_2026', 'U14Q10b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個數的 3/4 是 15，這個數是多少？',
   NULL,
   '20',
   'p5_ax_2026', 'U14Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=14 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '水果店運來一批蘋果，賣出了 3/5，正好賣出了 45 克，這批蘋果一共有多少克？',
   NULL,
   '75',
   'p5_ax_2026', 'U14Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '把小數 0.35 化成百分數。',
   '["A. 3.5%", "B. 35%", "C. 350%", "D. 0.35%"]'::jsonb,
   'B. 35%',
   'p5_ax_2026', 'U15Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '把小數 1.2 化成百分數。',
   '["A. 12%", "B. 1.2%", "C. 120%", "D. 0.12%"]'::jsonb,
   'C. 120%',
   'p5_ax_2026', 'U15Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '把分數 3/4 化成百分數。',
   '["A. 34%", "B. 75%", "C. 7.5%", "D. 0.75%"]'::jsonb,
   'B. 75%',
   'p5_ax_2026', 'U15Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '把分數 2/5 化成百分數。',
   '["A. 25%", "B. 4%", "C. 40%", "D. 2.5%"]'::jsonb,
   'C. 40%',
   'p5_ax_2026', 'U15Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把百分數 45% 化成小數。',
   NULL,
   '0.45',
   'p5_ax_2026', 'U15Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把百分數 120% 化成小數。',
   NULL,
   '1.2',
   'p5_ax_2026', 'U15Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把百分數 25% 化成最簡分數。',
   NULL,
   '1/4',
   'p5_ax_2026', 'U15Q6a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '把百分數 80% 化成最簡分數。',
   NULL,
   '4/5',
   'p5_ax_2026', 'U15Q6b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'multiple_choice',
   '六年級一班有 50 名學生，今天有 48 人出席，今天的出席率是多少（百分數，不需百分號）？',
   '["A. 96%", "B. 48%", "C. 92%", "D. 98%"]'::jsonb,
   'A. 96%',
   'p5_ax_2026', 'U15Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一件衣服原價 500 元，現在打八折出售，現在的售價是多少元？',
   NULL,
   '400',
   'p5_ax_2026', 'U15Q9a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一件衣服原價 500 元，現在打八折出售，便宜了多少元？',
   NULL,
   '100',
   'p5_ax_2026', 'U15Q9b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '小明把 2000 元存入銀行，年利率是 2.5%，一年後他可以得到利息多少元？',
   NULL,
   '50',
   'p5_ax_2026', 'U15Q10a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '小明把 2000 元存入銀行，年利率是 2.5%，一年後本金和利息一共多少元？',
   NULL,
   '2050',
   'p5_ax_2026', 'U15Q10b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個數的 30% 是 15，這個數是多少？',
   NULL,
   '50',
   'p5_ax_2026', 'U15Q11', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=15 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '一款手機原價 6000 元，先漲價 10%，再降價 10%，現在的售價是多少元？',
   NULL,
   '5940',
   'p5_ax_2026', 'U15Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=16 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一個圓的半徑是 4 厘米，它的直徑是多少厘米？',
   NULL,
   '8',
   'p5_ax_2026', 'U16Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=16 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '一個圓的直徑是 12 厘米，它的半徑是多少厘米？',
   NULL,
   '6',
   'p5_ax_2026', 'U16Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=16 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '圓規兩腳之間的距離是 3 厘米，畫出來的圓的半徑是多少厘米？',
   NULL,
   '3',
   'p5_ax_2026', 'U16Q7a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=16 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '圓規兩腳之間的距離是 3 厘米，畫出來的圓的直徑是多少厘米？',
   NULL,
   '6',
   'p5_ax_2026', 'U16Q7b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=16 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '在一個長 10 厘米、闊 6 厘米的長方形紙裡，畫一個最大的圓，這個圓的直徑是多少厘米？',
   NULL,
   '6',
   'p5_ax_2026', 'U16Q8a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=16 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '在一個長 10 厘米、闊 6 厘米的長方形紙裡，畫一個最大的圓，這個圓的半徑是多少厘米？',
   NULL,
   '3',
   'p5_ax_2026', 'U16Q8b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=16 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '在一個邊長是 8 厘米的正方形紙裡，畫一個最大的圓，這個圓的直徑是多少厘米？',
   NULL,
   '8',
   'p5_ax_2026', 'U16Q9a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=16 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '在一個邊長是 8 厘米的正方形紙裡，畫一個最大的圓，這個圓的半徑是多少厘米？',
   NULL,
   '4',
   'p5_ax_2026', 'U16Q9b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=16 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個圓的直徑擴大到原來的 3 倍，它的半徑擴大到原來的多少倍？',
   NULL,
   '3',
   'p5_ax_2026', 'U16Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=16 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '畫一個直徑是 5 厘米的圓，圓規兩腳之間的距離應該是多少厘米？',
   NULL,
   '2.5',
   'p5_ax_2026', 'U16Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=17 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '計算長方體的表面積：長 8 厘米，闊 5 厘米，高 4 厘米。（單位：平方厘米）',
   NULL,
   '184',
   'p5_ax_2026', 'U17Q2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=17 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算正方體的表面積：棱長是 6 厘米。（單位：平方厘米）',
   NULL,
   '216',
   'p5_ax_2026', 'U17Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=17 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算長方體的體積：長 10 厘米，闊 6 厘米，高 3 厘米。（單位：立方厘米）',
   NULL,
   '180',
   'p5_ax_2026', 'U17Q4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=17 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算正方體的體積：棱長是 5 厘米。（單位：立方厘米）',
   NULL,
   '125',
   'p5_ax_2026', 'U17Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=17 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '一個長方體的魚缸，長 60 厘米，闊 40 厘米，高 50 厘米，製作這個無蓋的魚缸至少需要多少平方厘米的玻璃？',
   NULL,
   '12400',
   'p5_ax_2026', 'U17Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=17 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '一個長方體的游泳池，長 50 米，闊 25 米，深 2 米，要在游泳池的四周和底面貼瓷磚，貼瓷磚的面積是多少平方米？',
   NULL,
   '1550',
   'p5_ax_2026', 'U17Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=17 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '用一根長 72 厘米的鐵絲焊接成一個長方體框架，長是 8 厘米，闊是 6 厘米，高是多少厘米？',
   NULL,
   '4',
   'p5_ax_2026', 'U17Q11a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=17 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個長方體框架，長 8 厘米，闊 6 厘米，高 4 厘米，這個長方體的體積是多少立方厘米？',
   NULL,
   '192',
   'p5_ax_2026', 'U17Q11b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=17 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '把兩個棱長是 3 厘米的正方體拼成一個長方體，這個長方體的表面積是多少平方厘米？',
   NULL,
   '90',
   'p5_ax_2026', 'U17Q12a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=17 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '把兩個棱長是 3 厘米的正方體拼成一個長方體，這個長方體的體積是多少立方厘米？',
   NULL,
   '54',
   'p5_ax_2026', 'U17Q12b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=18 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '計算下列數據的平均數：12、15、18、21、24。',
   NULL,
   '18',
   'p5_ax_2026', 'U18Q2', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=18 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '小明數學考試前四次的成績分別是 85 分、90 分、88 分、92 分，他這四次考試的平均成績是多少分？',
   NULL,
   '88.75',
   'p5_ax_2026', 'U18Q3', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=18 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '三個數的平均數是 25，其中兩個數分別是 22 和 28，第三個數是多少？',
   NULL,
   '25',
   'p5_ax_2026', 'U18Q4', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=18 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '五年級一班有 40 名學生，二班有 42 名學生，三班有 38 名學生，三個班平均每班有多少名學生？',
   NULL,
   '40',
   'p5_ax_2026', 'U18Q5', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=18 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '一輛汽車前 3 小時平均每小時行駛 65 米，後 2 小時一共行駛了 140 米，這輛汽車平均每小時行駛多少米？',
   NULL,
   '67',
   'p5_ax_2026', 'U18Q6', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=18 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '小明前三次數學考試的平均成績是 88 分，第四次考了 96 分，他四次考試的平均成績是多少分？',
   NULL,
   '90',
   'p5_ax_2026', 'U18Q7', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=18 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '有 5 個數，它們的平均數是 12，如果把其中一個數改成 18，這時 5 個數的平均數變成了 15，被改動的數原來是多少？',
   NULL,
   '3',
   'p5_ax_2026', 'U18Q8', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=18 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '水果店星期一到星期五分別賣出蘋果 25 克、30 克、28 克、32 克、35 克，平均每天賣出多少克蘋果？',
   NULL,
   '30',
   'p5_ax_2026', 'U18Q10', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=18 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '甲、乙、丙三個數的平均數是 36，乙、丙兩個數的平均數是 32，甲數是多少？',
   NULL,
   '44',
   'p5_ax_2026', 'U18Q12', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=18 ORDER BY t.lesson_number LIMIT 1), 'advanced', 'fill_in_number',
   '五年級兩個班參加數學考試，一班 40 人平均成績 85 分，二班 45 人平均成績 80 分，兩個班的總平均成績是多少分？（保留一位小數）',
   NULL,
   '82.4',
   'p5_ax_2026', 'U18Q13', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=19 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '香港某地 2025 年每月平均氣溫為 1月15、2月16、3月19、4月23、5月26、6月28、7月30、8月30、9月28、10月25、11月21、12月17 ℃。哪個月的平均氣溫最高？',
   '["A. 6 月", "B. 7 月或 8 月", "C. 9 月", "D. 5 月"]'::jsonb,
   'B. 7 月或 8 月',
   'p5_ax_2026', 'U19Q3a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=19 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '上題中哪個月的平均氣溫最低？',
   '["A. 12 月", "B. 2 月", "C. 1 月", "D. 11 月"]'::jsonb,
   'C. 1 月',
   'p5_ax_2026', 'U19Q3b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=19 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'multiple_choice',
   '小明從一年級到六年級身高分別為 120、125、130、138、145、152 厘米。從幾年級到幾年級身高增長最快？',
   '["A. 三到四年級", "B. 一到二年級", "C. 四到五年級", "D. 五到六年級"]'::jsonb,
   'A. 三到四年級',
   'p5_ax_2026', 'U19Q4a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=19 ORDER BY t.lesson_number LIMIT 1), 'basic', 'fill_in_number',
   '小明從一年級到六年級身高分別為 120、125、130、138、145、152 厘米，從一年級到六年級一共長高了多少厘米？',
   NULL,
   '32',
   'p5_ax_2026', 'U19Q4b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=19 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '某超市 2025 年上半年營業額為 1月20、2月18、3月25、4月30、5月28、6月35 萬元。哪個月的營業額最高？',
   '["A. 4 月", "B. 6 月", "C. 3 月", "D. 5 月"]'::jsonb,
   'B. 6 月',
   'p5_ax_2026', 'U19Q5a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=19 ORDER BY t.lesson_number LIMIT 1), 'basic', 'multiple_choice',
   '某超市上半年營業額為 1月20、2月18、3月25、4月30、5月28、6月35 萬元。哪個月的營業額最低？',
   '["A. 1 月", "B. 2 月", "C. 3 月", "D. 5 月"]'::jsonb,
   'B. 2 月',
   'p5_ax_2026', 'U19Q5b', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=19 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '某超市上半年營業額為 1月20、2月18、3月25、4月30、5月28、6月35 萬元。上半年平均每月的營業額是多少萬元？',
   NULL,
   '26',
   'p5_ax_2026', 'U19Q5c', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=19 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個折線圖中，用 1 厘米的線段代表 5℃，那麼代表 25℃ 的線段應該畫多少厘米長？',
   NULL,
   '5',
   'p5_ax_2026', 'U19Q10a', true),
  ((SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5 AND u.unit_number=19 ORDER BY t.lesson_number LIMIT 1), 'enhancement', 'fill_in_number',
   '一個折線圖中，用 1 厘米的線段代表 5℃，4 厘米長的線段代表多少℃？',
   NULL,
   '20',
   'p5_ax_2026', 'U19Q10b', true);

COMMIT;

-- Sanity:
-- SELECT count(*) FROM assessment_questions WHERE source_paper='p5_ax_2026' AND is_active;  -- expect 187
-- SELECT source_paper, count(*) FROM assessment_questions WHERE topic_id IN (
--   SELECT t.id FROM curriculum_topics t JOIN curriculum_units u ON u.id=t.unit_id WHERE u.grade=5)
--   GROUP BY source_paper;