-- Sprint 7: 學前評估 (Pre-enrollment Assessment)
-- Public-facing, no-login assessment for lead generation

CREATE TABLE assessment_sessions (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  grade         int         NOT NULL,    -- 5 or 6
  semester      text        NOT NULL,    -- '上' or '下'
  grade_level   text        NOT NULL,    -- display string e.g. '小五上學期'
  student_name  text        NOT NULL,
  school_name   text,
  parent_phone  text,
  parent_email  text,
  -- JSON array of answer objects:
  -- [{question_id, question_text, question_type, correct_answer,
  --   student_answer, is_correct, category_id, category_code, module_name}]
  answers       jsonb       NOT NULL DEFAULT '[]',
  -- Pre-computed report generated by Gemini after submission
  report_data   jsonb,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- RLS: fully public insert (no auth needed) + public read by id
ALTER TABLE assessment_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "assessment_public_insert"
  ON assessment_sessions FOR INSERT
  WITH CHECK (true);

CREATE POLICY "assessment_public_select"
  ON assessment_sessions FOR SELECT
  USING (true);

-- Index for teacher admin view (ordered by date)
CREATE INDEX idx_assessment_sessions_created_at
  ON assessment_sessions (created_at DESC);
